import { Prisma, PrismaClient } from "../node_modules/.prisma/client/index";

const prisma = new PrismaClient();

// Paste your products.json content here, or import it:
// import data from "./products.json";
// For now, the data is embedded below matching your products.json exactly.

const data = [
  {
    name: "PVC Fittings",
    slug: "pvc-fittings",
    products: [
      {
        name: "SCH 80 PVC Union, 2 Inch, 4 Inch Pipe Fitting",
        slug: "sch80-pvc-union",
        image: "/images/products/sch80-pvc-union.jpg",
        preview: "SCH 80 PVC union for pipe connection with easy disassembly for maintenance.",
        description: "SCH 80 PVC union is designed for connecting pipes while allowing easy disassembly for inspection and maintenance. It features a three-piece construction with a strong sealing O-ring, excellent chemical and corrosion resistance, and is manufactured to ASTM D 2467 standard. Suitable for industrial, agricultural, and chemical piping systems.",
        specs: [
          { key: "material", value: "PVC / UPVC" },
          { key: "color", value: "Gray" },
          { key: "standard", value: "ASTM D 2467, SCH 80" },
          { key: "size", value: '1/4" - 4"' },
          { key: "connection", value: "Socket (Solvent Weld)" },
          { key: "pressure_rating", value: "SCH 80" },
          { key: "working_temperature", value: "Up to 60°C" },
          { key: "application", value: "Industrial piping, chemical processing, water treatment" },
        ],
        tables: [
          { size: '1/2"', od_mm: "21.3", weight_kg: "0.08" },
          { size: '3/4"', od_mm: "26.7", weight_kg: "0.12" },
          { size: '1"', od_mm: "33.4", weight_kg: "0.18" },
          { size: '1-1/4"', od_mm: "42.2", weight_kg: "0.28" },
          { size: '1-1/2"', od_mm: "48.3", weight_kg: "0.38" },
          { size: '2"', od_mm: "60.3", weight_kg: "0.58" },
          { size: '2-1/2"', od_mm: "73.0", weight_kg: "0.95" },
          { size: '3"', od_mm: "88.9", weight_kg: "1.45" },
          { size: '4"', od_mm: "114.3", weight_kg: "2.50" },
        ],
      },
      {
        name: "SCH80 PVC Using On The End Cap For Pipe",
        slug: "sch80-pvc-end-cap",
        image: "/images/products/sch80-pvc-end-cap.jpg",
        preview: "SCH 80 PVC end cap for sealing pipe ends in pressure systems.",
        description: "SCH 80 PVC end cap is used to close off the end of a pipe run. Manufactured to ASTM D 2467 standard, it provides a pressure-tight seal and is resistant to a wide range of chemicals. Suitable for temporary or permanent pipe termination in water supply, chemical, and industrial systems.",
        specs: [
          { key: "material", value: "PVC / UPVC" },
          { key: "color", value: "Gray" },
          { key: "standard", value: "ASTM D 2467, SCH 80" },
          { key: "size", value: '1/4" - 12"' },
          { key: "connection", value: "Socket (Solvent Weld)" },
          { key: "pressure_rating", value: "SCH 80" },
          { key: "working_temperature", value: "Up to 60°C" },
          { key: "application", value: "Pipe termination, pressure systems, water and chemical lines" },
        ],
        tables: [
          { size: '1/2"', od_mm: "21.3", weight_kg: "0.03" },
          { size: '3/4"', od_mm: "26.7", weight_kg: "0.05" },
          { size: '1"', od_mm: "33.4", weight_kg: "0.07" },
          { size: '1-1/4"', od_mm: "42.2", weight_kg: "0.11" },
          { size: '1-1/2"', od_mm: "48.3", weight_kg: "0.15" },
          { size: '2"', od_mm: "60.3", weight_kg: "0.22" },
          { size: '3"', od_mm: "88.9", weight_kg: "0.55" },
          { size: '4"', od_mm: "114.3", weight_kg: "0.95" },
        ],
      },
      {
        name: "SCH 80 PVC One Piece Flange, 8 Inch Normal Size",
        slug: "sch80-pvc-one-piece-flange",
        image: "/images/products/sch80-pvc-one-piece-flange.jpg",
        preview: "SCH 80 PVC one piece flange for bolted pipe connections up to 8 inch.",
        description: "SCH 80 PVC one piece (solid) flange is used to connect piping to equipment such as pumps, valves, and tanks. Manufactured to ASTM D 2467 standard with pre-drilled bolt holes conforming to ANSI B16.5 dimensions. Available up to 8 inch, it provides leak-free flanged connections in chemical, water treatment, and industrial applications.",
        specs: [
          { key: "material", value: "PVC / UPVC" },
          { key: "color", value: "Gray" },
          { key: "standard", value: "ASTM D 2467, SCH 80 / ANSI B16.5" },
          { key: "size", value: '1/2" - 8"' },
          { key: "connection", value: "Socket (Solvent Weld) with bolt flange face" },
          { key: "pressure_rating", value: "SCH 80" },
          { key: "working_temperature", value: "Up to 60°C" },
          { key: "application", value: "Pump connections, tank outlets, equipment flanging, chemical plants" },
        ],
        // Each row stored as exact JSON matching the JSON file
        tables: [
          { size: '1"', od_mm: "33.4", bolt_circle_mm: "79.4", no_bolts: "4" },
          { size: '1-1/2"', od_mm: "48.3", bolt_circle_mm: "98.4", no_bolts: "4" },
          { size: '2"', od_mm: "60.3", bolt_circle_mm: "120.6", no_bolts: "4" },
          { size: '3"', od_mm: "88.9", bolt_circle_mm: "152.4", no_bolts: "4" },
          { size: '4"', od_mm: "114.3", bolt_circle_mm: "190.5", no_bolts: "8" },
          { size: '6"', od_mm: "168.3", bolt_circle_mm: "241.3", no_bolts: "8" },
          { size: '8"', od_mm: "219.1", bolt_circle_mm: "298.4", no_bolts: "8" },
        ],
      },
      {
        name: "ASTM D 2467 SCH 80 PVC Reducing Tee",
        slug: "sch80-pvc-equal-reducing-tee",
        image: "/images/products/sch80-pvc-equal-reducing-tee.jpg",
        preview: "SCH 80 PVC reducing tee to connect three pipes of equal or different sizes.",
        description: "SCH 80 PVC reducing tee allows branching of a pipeline with a smaller outlet branch. Manufactured to ASTM D 2467 standard, it offers excellent pressure resistance and chemical compatibility. Available in reducing configurations for flexible piping layout design.",
        specs: [
          { key: "material", value: "PVC / UPVC" },
          { key: "color", value: "Gray" },
          { key: "standard", value: "ASTM D 2467, SCH 80" },
          { key: "size", value: '1/4" - 8" (run) x various branch sizes' },
          { key: "connection", value: "Socket (Solvent Weld)" },
          { key: "pressure_rating", value: "SCH 80" },
          { key: "working_temperature", value: "Up to 60°C" },
          { key: "application", value: "Industrial pipelines, chemical distribution, water treatment branching" },
        ],
        tables: [
          { run_size: '3/4"', branch_size: '1/2"' },
          { run_size: '1"', branch_size: '3/4"' },
          { run_size: '1-1/2"', branch_size: '1"' },
          { run_size: '2"', branch_size: '1-1/2"' },
          { run_size: '3"', branch_size: '2"' },
          { run_size: '4"', branch_size: '3"' },
          { run_size: '6"', branch_size: '4"' },
          { run_size: '8"', branch_size: '6"' },
        ],
      },
      {
        name: "NPT Threaded SCH 80 PVC Male Adaptor Coupling",
        slug: "sch80-pvc-male-adaptor",
        image: "/images/products/sch80-pvc-male-adaptor.jpg",
        preview: "SCH 80 PVC male adaptor with NPT thread for socket-to-thread transitions.",
        description: "SCH 80 PVC male adaptor coupling connects a socket-end pipe to an NPT female threaded fitting or equipment port. Manufactured to ASTM D 2467 standard with NPT threads per ANSI/ASME B1.20.1. Ideal for transitions from solvent-welded pipe systems to threaded valves, pumps, or instrumentation.",
        specs: [
          { key: "material", value: "PVC / UPVC" },
          { key: "color", value: "Gray" },
          { key: "standard", value: "ASTM D 2467, SCH 80" },
          { key: "thread_standard", value: "NPT (ANSI/ASME B1.20.1)" },
          { key: "size", value: '1/4" - 4"' },
          { key: "connection", value: "Socket (Solvent Weld) x NPT Male Thread" },
          { key: "pressure_rating", value: "SCH 80" },
          { key: "working_temperature", value: "Up to 60°C" },
          { key: "application", value: "Pump and valve connections, threaded pipe transitions, instrumentation hookup" },
        ],
        tables: [
          { size: '1/4"', npt_thread: '1/4" NPT' },
          { size: '3/8"', npt_thread: '3/8" NPT' },
          { size: '1/2"', npt_thread: '1/2" NPT' },
          { size: '3/4"', npt_thread: '3/4" NPT' },
          { size: '1"', npt_thread: '1" NPT' },
          { size: '1-1/4"', npt_thread: '1-1/4" NPT' },
          { size: '1-1/2"', npt_thread: '1-1/2" NPT' },
          { size: '2"', npt_thread: '2" NPT' },
          { size: '3"', npt_thread: '3" NPT' },
          { size: '4"', npt_thread: '4" NPT' },
        ],
      },
      {
        name: "SCH 80 Fitting PVC 45 Degree Elbow Bend Glue Connection",
        slug: "sch80-pvc-45-elbow",
        image: "/images/products/sch80-pvc-45-elbow.jpg",
        preview: "SCH 80 PVC 45° elbow for directional changes in piping via solvent weld.",
        description: "SCH 80 PVC 45 degree elbow provides a 45° change in pipe direction using solvent cement (glue) socket connections. Manufactured to ASTM D 2467 standard, it is suited for industrial systems where a gradual directional change is required, reducing turbulence compared to a 90° elbow. Excellent chemical and UV resistance.",
        specs: [
          { key: "material", value: "PVC / UPVC" },
          { key: "color", value: "Gray" },
          { key: "standard", value: "ASTM D 2467, SCH 80" },
          { key: "angle", value: "45°" },
          { key: "size", value: '1/4" - 8"' },
          { key: "connection", value: "Socket (Solvent Weld / Glue)" },
          { key: "pressure_rating", value: "SCH 80" },
          { key: "working_temperature", value: "Up to 60°C" },
          { key: "application", value: "Industrial pipelines, chemical plants, irrigation systems" },
        ],
        tables: [
          { size: '1/2"', weight_kg: "0.04" },
          { size: '3/4"', weight_kg: "0.06" },
          { size: '1"', weight_kg: "0.09" },
          { size: '1-1/4"', weight_kg: "0.15" },
          { size: '1-1/2"', weight_kg: "0.20" },
          { size: '2"', weight_kg: "0.32" },
          { size: '3"', weight_kg: "0.80" },
          { size: '4"', weight_kg: "1.40" },
          { size: '6"', weight_kg: "3.50" },
          { size: '8"', weight_kg: "7.00" },
        ],
      },
      {
        name: "SCH 80 PVC Coupling, Socket Couplers, Using Quick Connection",
        slug: "sch80-pvc-coupling",
        image: "/images/products/sch80-pvc-coupling.jpg",
        preview: "SCH 80 PVC socket coupling for joining two pipes end-to-end.",
        description: "SCH 80 PVC socket coupling connects two pipes of the same diameter end-to-end using solvent cement. Manufactured to ASTM D 2467 standard, it provides a high-pressure, leak-free joint. Used in industrial, chemical, and water treatment piping systems for straight-run pipe joining or pipe repairs.",
        specs: [
          { key: "material", value: "PVC / UPVC" },
          { key: "color", value: "Gray" },
          { key: "standard", value: "ASTM D 2467, SCH 80" },
          { key: "size", value: '1/4" - 12"' },
          { key: "connection", value: "Socket x Socket (Solvent Weld)" },
          { key: "pressure_rating", value: "SCH 80" },
          { key: "working_temperature", value: "Up to 60°C" },
          { key: "application", value: "Pipe joining, water supply, chemical distribution, irrigation" },
        ],
        tables: [
          { size: '1/4"', weight_kg: "0.02" },
          { size: '3/8"', weight_kg: "0.02" },
          { size: '1/2"', weight_kg: "0.03" },
          { size: '3/4"', weight_kg: "0.05" },
          { size: '1"', weight_kg: "0.07" },
          { size: '1-1/4"', weight_kg: "0.12" },
          { size: '1-1/2"', weight_kg: "0.16" },
          { size: '2"', weight_kg: "0.25" },
          { size: '3"', weight_kg: "0.60" },
          { size: '4"', weight_kg: "1.05" },
          { size: '6"', weight_kg: "2.60" },
          { size: '8"', weight_kg: "5.20" },
        ],
      },
      {
        name: "Gray Color SCH 80 PVC 90 Degree Elbow",
        slug: "sch80-pvc-90-elbow",
        image: "/images/products/sch80-pvc-90-elbow.jpg",
        preview: "SCH 80 PVC 90° elbow in gray for right-angle pipe direction changes.",
        description: "SCH 80 PVC 90 degree elbow is used to change pipe direction at a right angle. Manufactured to ASTM D 2467 standard in gray color, it features socket ends for solvent cement connection. The fitting offers high pressure rating, excellent chemical resistance, and long service life in industrial and chemical piping applications.",
        specs: [
          { key: "material", value: "PVC / UPVC" },
          { key: "color", value: "Gray" },
          { key: "standard", value: "ASTM D 2467, SCH 80" },
          { key: "angle", value: "90°" },
          { key: "size", value: '1/4" - 8"' },
          { key: "connection", value: "Socket (Solvent Weld)" },
          { key: "pressure_rating", value: "SCH 80" },
          { key: "working_temperature", value: "Up to 60°C" },
          { key: "application", value: "Industrial and chemical piping, water treatment, irrigation" },
        ],
        tables: [
          { size: '1/4"', weight_kg: "0.02" },
          { size: '3/8"', weight_kg: "0.03" },
          { size: '1/2"', weight_kg: "0.05" },
          { size: '3/4"', weight_kg: "0.08" },
          { size: '1"', weight_kg: "0.12" },
          { size: '1-1/4"', weight_kg: "0.20" },
          { size: '1-1/2"', weight_kg: "0.28" },
          { size: '2"', weight_kg: "0.45" },
          { size: '3"', weight_kg: "1.10" },
          { size: '4"', weight_kg: "2.00" },
          { size: '6"', weight_kg: "5.00" },
          { size: '8"', weight_kg: "9.50" },
        ],
      },
      {
        name: "ASTM D 1785 Pipe Fittings SCH80 PVC Equal Tee",
        slug: "sch80-pvc-equal-tee",
        image: "/images/products/sch80-pvc-equal-tee.jpg",
        preview: "SCH 80 PVC equal tee for creating equal three-way pipe branches.",
        description: "SCH 80 PVC equal tee provides a T-shaped branch connection where all three outlets are the same size. Manufactured to ASTM D 1785 / ASTM D 2467 standard, it is suitable for splitting or combining flow in industrial, chemical processing, and water treatment pipelines. Gray color, socket end connections.",
        specs: [
          { key: "material", value: "PVC / UPVC" },
          { key: "color", value: "Gray" },
          { key: "standard", value: "ASTM D 1785 / ASTM D 2467, SCH 80" },
          { key: "size", value: '1/4" - 8"' },
          { key: "connection", value: "Socket x Socket x Socket (Solvent Weld)" },
          { key: "pressure_rating", value: "SCH 80" },
          { key: "working_temperature", value: "Up to 60°C" },
          { key: "application", value: "Pipeline branching, chemical distribution, water and irrigation systems" },
        ],
        tables: [
          { size: '1/4"', weight_kg: "0.03" },
          { size: '3/8"', weight_kg: "0.04" },
          { size: '1/2"', weight_kg: "0.06" },
          { size: '3/4"', weight_kg: "0.10" },
          { size: '1"', weight_kg: "0.15" },
          { size: '1-1/4"', weight_kg: "0.25" },
          { size: '1-1/2"', weight_kg: "0.35" },
          { size: '2"', weight_kg: "0.55" },
          { size: '3"', weight_kg: "1.35" },
          { size: '4"', weight_kg: "2.40" },
          { size: '6"', weight_kg: "6.00" },
          { size: '8"', weight_kg: "12.00" },
        ],
      },
      {
        name: "Up To 12 Inch SCH 80 PVC Reducers Coupling For Pipe",
        slug: "sch80-pvc-reducer-coupling",
        image: "/images/products/sch80-pvc-reducer-coupling.jpg",
        preview: "SCH 80 PVC reducer coupling to connect pipes of two different diameters up to 12 inch.",
        description: "SCH 80 PVC reducer coupling (concentric reducer) connects two pipes of different diameters in a straight run. Available in sizes up to 12 inch, manufactured to ASTM D 2467 standard. Used where pipe diameter changes are required in industrial, chemical, and water treatment piping systems.",
        specs: [
          { key: "material", value: "PVC / UPVC" },
          { key: "color", value: "Gray" },
          { key: "standard", value: "ASTM D 2467, SCH 80" },
          { key: "size", value: '3/4" x 1/2" up to 12" x 10"' },
          { key: "connection", value: "Socket x Socket (Solvent Weld)" },
          { key: "pressure_rating", value: "SCH 80" },
          { key: "working_temperature", value: "Up to 60°C" },
          { key: "application", value: "Pipe size transitions, industrial and chemical pipelines, water treatment" },
        ],
        tables: [
          { large_end: '3/4"', small_end: '1/2"' },
          { large_end: '1"', small_end: '3/4"' },
          { large_end: '1-1/4"', small_end: '1"' },
          { large_end: '1-1/2"', small_end: '1-1/4"' },
          { large_end: '2"', small_end: '1-1/2"' },
          { large_end: '2-1/2"', small_end: '2"' },
          { large_end: '3"', small_end: '2"' },
          { large_end: '4"', small_end: '3"' },
          { large_end: '6"', small_end: '4"' },
          { large_end: '8"', small_end: '6"' },
          { large_end: '10"', small_end: '8"' },
          { large_end: '12"', small_end: '10"' },
        ],
      },
      {
        name: "SCH 80 PVC Reducer Bushing Connect Pipe And Fittings",
        slug: "sch80-pvc-reducer-bushing",
        image: "/images/products/sch80-pvc-reducer-bushing.jpg",
        preview: "SCH 80 PVC reducer bushing for reducing fittings to a smaller pipe size.",
        description: "SCH 80 PVC reducer bushing is inserted inside a larger socket fitting to reduce it to a smaller pipe size. Manufactured to ASTM D 2467 standard, it provides a compact and cost-effective size reduction solution without the need for a separate reducer coupling.",
        specs: [
          { key: "material", value: "PVC / UPVC" },
          { key: "color", value: "Gray" },
          { key: "standard", value: "ASTM D 2467, SCH 80" },
          { key: "size", value: '3/4" x 1/2" up to 6" x 4"' },
          { key: "connection", value: "Spigot (male socket) x Socket (Solvent Weld)" },
          { key: "pressure_rating", value: "SCH 80" },
          { key: "working_temperature", value: "Up to 60°C" },
          { key: "application", value: "Size reduction within fittings, industrial and chemical systems" },
        ],
        tables: [
          { spigot: '3/4"', socket: '1/2"' },
          { spigot: '1"', socket: '3/4"' },
          { spigot: '1-1/4"', socket: '1"' },
          { spigot: '1-1/2"', socket: '1-1/4"' },
          { spigot: '2"', socket: '1-1/2"' },
          { spigot: '3"', socket: '2"' },
          { spigot: '4"', socket: '3"' },
          { spigot: '6"', socket: '4"' },
        ],
      },
      {
        name: "Type SCH 80 PVC Female Adaptor",
        slug: "sch80-pvc-female-adaptor",
        image: "/images/products/sch80-pvc-female-adaptor.jpg",
        preview: "SCH 80 PVC female adaptor for transitioning from socket to NPT male thread.",
        description: "SCH 80 PVC female adaptor connects a solvent-welded pipe to an NPT male threaded fitting or equipment. Manufactured to ASTM D 2467 with NPT threads per ANSI/ASME B1.20.1 standard. Provides a reliable transition between solvent-weld and threaded piping systems.",
        specs: [
          { key: "material", value: "PVC / UPVC" },
          { key: "color", value: "Gray" },
          { key: "standard", value: "ASTM D 2467, SCH 80" },
          { key: "thread_standard", value: "NPT (ANSI/ASME B1.20.1)" },
          { key: "size", value: '1/4" - 4"' },
          { key: "connection", value: "Socket (Solvent Weld) x NPT Female Thread" },
          { key: "pressure_rating", value: "SCH 80" },
          { key: "working_temperature", value: "Up to 60°C" },
          { key: "application", value: "Thread-to-socket transitions, valve connections, pump inlets" },
        ],
        tables: [
          { size: '1/4"', npt_thread: '1/4" NPT' },
          { size: '3/8"', npt_thread: '3/8" NPT' },
          { size: '1/2"', npt_thread: '1/2" NPT' },
          { size: '3/4"', npt_thread: '3/4" NPT' },
          { size: '1"', npt_thread: '1" NPT' },
          { size: '1-1/4"', npt_thread: '1-1/4" NPT' },
          { size: '1-1/2"', npt_thread: '1-1/2" NPT' },
          { size: '2"', npt_thread: '2" NPT' },
          { size: '3"', npt_thread: '3" NPT' },
          { size: '4"', npt_thread: '4" NPT' },
        ],
      },
      {
        name: "SCH80 PVC Tank Adaptor",
        slug: "sch80-pvc-tank-adaptor",
        image: "/images/products/sch80-pvc-tank-adaptor.jpg",
        preview: "SCH 80 PVC tank adaptor for fitting pipes through tank walls.",
        description: "SCH 80 PVC tank adaptor (also known as a bulkhead fitting) is used to provide a leak-proof through-wall connection on tanks, reservoirs, or vessels. It features a nut and washer for clamping to the tank wall and is compatible with socket or threaded connections on both sides. Manufactured to ASTM D 2467 standard.",
        specs: [
          { key: "material", value: "PVC / UPVC" },
          { key: "color", value: "Gray" },
          { key: "standard", value: "ASTM D 2467, SCH 80" },
          { key: "size", value: '1/2" - 4"' },
          { key: "connection", value: "Socket / NPT Thread x Tank Wall Mount" },
          { key: "pressure_rating", value: "SCH 80" },
          { key: "seal", value: "EPDM / NBR rubber gasket" },
          { key: "working_temperature", value: "Up to 60°C" },
          { key: "application", value: "Chemical tanks, water storage tanks, reservoirs, industrial vessels" },
        ],
        tables: [
          { size: '1/2"', hole_dia_mm: "30" },
          { size: '3/4"', hole_dia_mm: "36" },
          { size: '1"', hole_dia_mm: "44" },
          { size: '1-1/4"', hole_dia_mm: "54" },
          { size: '1-1/2"', hole_dia_mm: "62" },
          { size: '2"', hole_dia_mm: "76" },
          { size: '3"', hole_dia_mm: "105" },
          { size: '4"', hole_dia_mm: "135" },
        ],
      },
      {
        name: "SCH80 UPVC Female Thread Tank Adaptor",
        slug: "sch80-upvc-female-thread-tank-adaptor",
        image: "/images/products/sch80-upvc-female-thread-tank-adaptor.jpg",
        preview: "SCH 80 UPVC tank adaptor with female NPT threads on both sides.",
        description: "SCH 80 UPVC female thread tank adaptor provides a through-wall bulkhead connection with female NPT threads on both the inner and outer sides of the tank wall. Allows screwed pipe connections on both sides for maximum installation flexibility. Includes rubber gaskets for leak-proof sealing.",
        specs: [
          { key: "material", value: "UPVC" },
          { key: "color", value: "Gray" },
          { key: "standard", value: "SCH 80" },
          { key: "thread_standard", value: "NPT Female Both Sides" },
          { key: "size", value: '1/2" - 4"' },
          { key: "connection", value: "NPT Female Thread x Tank Wall Mount x NPT Female Thread" },
          { key: "seal", value: "EPDM / NBR rubber gasket" },
          { key: "working_temperature", value: "Up to 60°C" },
          { key: "application", value: "Chemical tanks, water tanks, industrial storage vessels" },
        ],
        tables: [
          { size: '1/2"' },
          { size: '3/4"' },
          { size: '1"' },
          { size: '1-1/4"' },
          { size: '1-1/2"' },
          { size: '2"' },
          { size: '3"' },
          { size: '4"' },
        ],
      },
      {
        name: "SCH80 UPVC Female Elbow 90 Degree",
        slug: "sch80-upvc-female-elbow-90",
        image: "/images/products/sch80-upvc-female-elbow-90.jpg",
        preview: "SCH 80 UPVC 90° elbow with female NPT threads on both ends.",
        description: "SCH 80 UPVC female elbow 90 degree provides a right-angle directional change with female NPT threads on both ends. Used to connect threaded pipes or fittings at 90° in chemical, industrial, and water supply systems. Manufactured in SCH 80 wall thickness for high-pressure applications.",
        specs: [
          { key: "material", value: "UPVC" },
          { key: "color", value: "Gray" },
          { key: "standard", value: "SCH 80" },
          { key: "thread_standard", value: "NPT Female Both Ends" },
          { key: "angle", value: "90°" },
          { key: "size", value: '1/4" - 3"' },
          { key: "connection", value: "NPT Female Thread x NPT Female Thread" },
          { key: "pressure_rating", value: "SCH 80" },
          { key: "working_temperature", value: "Up to 60°C" },
          { key: "application", value: "Threaded pipe systems, water supply, chemical lines" },
        ],
        tables: [
          { size: '1/4"' },
          { size: '3/8"' },
          { size: '1/2"' },
          { size: '3/4"' },
          { size: '1"' },
          { size: '1-1/4"' },
          { size: '1-1/2"' },
          { size: '2"' },
          { size: '3"' },
        ],
      },
      {
        name: "PVC SCH80 Flow Meter Barrel Nipple",
        slug: "sch80-pvc-flow-meter-barrel-nipple",
        image: "/images/products/sch80-pvc-flow-meter-barrel-nipple.jpg",
        preview: "SCH 80 PVC barrel nipple for flow meter installation in pipe systems.",
        description: "SCH 80 PVC flow meter barrel nipple is a short-length threaded pipe nipple used specifically for the installation of flow meters and instrumentation. It features NPT male threads on both ends and is manufactured in SCH 80 wall thickness to withstand pressure and chemical exposure.",
        specs: [
          { key: "material", value: "PVC / UPVC" },
          { key: "color", value: "Gray" },
          { key: "standard", value: "SCH 80" },
          { key: "thread_standard", value: "NPT Male Both Ends" },
          { key: "size", value: '1/2" - 2"' },
          { key: "connection", value: "NPT Male Thread x NPT Male Thread" },
          { key: "pressure_rating", value: "SCH 80" },
          { key: "working_temperature", value: "Up to 60°C" },
          { key: "application", value: "Flow meter installation, instrumentation connections, pipe extensions" },
        ],
        tables: [
          { size: '1/2"', length_options: "25mm, 50mm, 75mm, 100mm" },
          { size: '3/4"', length_options: "25mm, 50mm, 75mm, 100mm" },
          { size: '1"', length_options: "25mm, 50mm, 75mm, 100mm" },
          { size: '1-1/2"', length_options: "50mm, 75mm, 100mm, 150mm" },
          { size: '2"', length_options: "50mm, 75mm, 100mm, 150mm" },
        ],
      },
      {
        name: "PVC Water Nozzle",
        slug: "pvc-water-nozzle",
        image: "/images/products/pvc-water-nozzle.jpg",
        preview: "PVC water nozzle for controlled water discharge in irrigation and industrial use.",
        description: "PVC water nozzle is used to control the flow and direction of water discharge in irrigation, cooling, and industrial spray applications. Made from high-quality PVC with good chemical resistance and UV stability. Available in various orifice sizes and thread connections.",
        specs: [
          { key: "material", value: "PVC" },
          { key: "color", value: "Gray" },
          { key: "size", value: '1/4" - 2"' },
          { key: "connection", value: "NPT Male or Female Thread" },
          { key: "application", value: "Irrigation, spray systems, cooling towers, industrial washing" },
        ],
        tables: [
          { size: '1/4"', orifice_mm: "3" },
          { size: '3/8"', orifice_mm: "5" },
          { size: '1/2"', orifice_mm: "8" },
          { size: '3/4"', orifice_mm: "12" },
          { size: '1"', orifice_mm: "16" },
        ],
      },
      {
        name: "PVC Reducing Barrel Nipple",
        slug: "pvc-reducing-barrel-nipple",
        image: "/images/products/pvc-reducing-barrel-nipple.jpg",
        preview: "PVC reducing barrel nipple for connecting two different pipe thread sizes in line.",
        description: "PVC reducing barrel nipple (hex nipple) connects two different NPT thread sizes in a straight run. Used for compact size reductions where a full reducer coupling is not practical. Available in SCH 80 wall thickness with NPT threads on both ends.",
        specs: [
          { key: "material", value: "PVC / UPVC" },
          { key: "color", value: "Gray" },
          { key: "standard", value: "SCH 80" },
          { key: "thread_standard", value: "NPT" },
          { key: "size", value: '3/4" x 1/2" up to 2" x 1"' },
          { key: "connection", value: "NPT Male (large) x NPT Male (small)" },
          { key: "working_temperature", value: "Up to 60°C" },
          { key: "application", value: "Threaded pipe size transitions, inline reductions, chemical and water systems" },
        ],
        tables: [
          { large_end: '3/4"', small_end: '1/2"' },
          { large_end: '1"', small_end: '3/4"' },
          { large_end: '1-1/4"', small_end: '1"' },
          { large_end: '1-1/2"', small_end: '1-1/4"' },
          { large_end: '2"', small_end: '1-1/2"' },
          { large_end: '2"', small_end: '1"' },
        ],
      },
      {
        name: "PVC SCH80 Female Bush",
        slug: "sch80-pvc-female-bush",
        image: "/images/products/sch80-pvc-female-bush.jpg",
        preview: "SCH 80 PVC female bush for reducing a large female thread to a smaller size.",
        description: "SCH 80 PVC female bush (also called a hex bushing) is used to reduce an internal female thread to a smaller male thread. Commonly used in threaded fittings, valves, and equipment ports to adapt to a smaller pipe size without additional fittings.",
        specs: [
          { key: "material", value: "PVC / UPVC" },
          { key: "color", value: "Gray" },
          { key: "standard", value: "SCH 80" },
          { key: "thread_standard", value: "NPT" },
          { key: "size", value: '3/4" x 1/2" up to 3" x 2"' },
          { key: "connection", value: "NPT Female (large) x NPT Male (small)" },
          { key: "pressure_rating", value: "SCH 80" },
          { key: "working_temperature", value: "Up to 60°C" },
          { key: "application", value: "Thread size reduction, valve adaptation, equipment hookup" },
        ],
        tables: [
          { female_npt: '3/4"', male_npt: '1/2"' },
          { female_npt: '1"', male_npt: '3/4"' },
          { female_npt: '1-1/4"', male_npt: '1"' },
          { female_npt: '1-1/2"', male_npt: '1-1/4"' },
          { female_npt: '2"', male_npt: '1-1/2"' },
          { female_npt: '3"', male_npt: '2"' },
        ],
      },
      {
        name: "PVC SCH80 Male and Female Bush",
        slug: "sch80-pvc-male-female-bush",
        image: "/images/products/sch80-pvc-male-female-bush.jpg",
        preview: "SCH 80 PVC bush with male and female NPT threads for inline adaptations.",
        description: "SCH 80 PVC male and female bush combines male NPT thread on one end and female NPT thread on the other, used for inline adaptations between threaded pipe systems or for extending a thread connection. Manufactured in SCH 80 wall thickness for high-pressure applications.",
        specs: [
          { key: "material", value: "PVC / UPVC" },
          { key: "color", value: "Gray" },
          { key: "standard", value: "SCH 80" },
          { key: "thread_standard", value: "NPT" },
          { key: "size", value: '1/2" - 3"' },
          { key: "connection", value: "NPT Male x NPT Female" },
          { key: "pressure_rating", value: "SCH 80" },
          { key: "working_temperature", value: "Up to 60°C" },
          { key: "application", value: "Thread extensions, inline adaptation, pipe and valve connections" },
        ],
        tables: [
          { size: '1/2"' },
          { size: '3/4"' },
          { size: '1"' },
          { size: '1-1/4"' },
          { size: '1-1/2"' },
          { size: '2"' },
          { size: '3"' },
        ],
      },
      {
        name: "PVC Bend",
        slug: "pvc-bend",
        image: "/images/products/pvc-bend.jpg",
        preview: "PVC pipe bend for flexible directional changes in piping layouts.",
        description: "PVC bend provides directional changes in piping systems and is available in various angles including 11.25°, 22.5°, 45°, and 90°. Used in water supply, drainage, irrigation, and industrial pipe routing. Manufactured from high-quality PVC for durability and chemical resistance.",
        specs: [
          { key: "material", value: "PVC / UPVC" },
          { key: "color", value: "Gray" },
          { key: "angles_available", value: "11.25°, 22.5°, 45°, 90°" },
          { key: "size", value: '1/2" - 12"' },
          { key: "connection", value: "Socket (Solvent Weld) or Rubber Ring" },
          { key: "working_temperature", value: "Up to 60°C" },
          { key: "application", value: "Water supply, irrigation, drainage, industrial pipe routing" },
        ],
        tables: [
          { size: '1/2"' },
          { size: '3/4"' },
          { size: '1"' },
          { size: '1-1/2"' },
          { size: '2"' },
          { size: '3"' },
          { size: '4"' },
          { size: '6"' },
          { size: '8"' },
          { size: '10"' },
          { size: '12"' },
        ],
      },
      {
        name: "PVC SCH80 Male Elbow",
        slug: "sch80-pvc-male-elbow",
        image: "/images/products/sch80-pvc-male-elbow.jpg",
        preview: "SCH 80 PVC 90° elbow with one socket and one NPT male thread end.",
        description: "SCH 80 PVC male elbow provides a 90° directional change with a socket end on one side and an NPT male thread on the other. Used where a pipe run needs to change direction and connect to a female-threaded fitting or equipment. Manufactured to ASTM D 2467 standard.",
        specs: [
          { key: "material", value: "PVC / UPVC" },
          { key: "color", value: "Gray" },
          { key: "standard", value: "ASTM D 2467, SCH 80" },
          { key: "thread_standard", value: "NPT Male (ANSI/ASME B1.20.1)" },
          { key: "angle", value: "90°" },
          { key: "size", value: '1/4" - 3"' },
          { key: "connection", value: "Socket (Solvent Weld) x NPT Male Thread" },
          { key: "pressure_rating", value: "SCH 80" },
          { key: "working_temperature", value: "Up to 60°C" },
          { key: "application", value: "Pipe direction changes to threaded fittings, valve connections" },
        ],
        tables: [
          { size: '1/4"' },
          { size: '3/8"' },
          { size: '1/2"' },
          { size: '3/4"' },
          { size: '1"' },
          { size: '1-1/4"' },
          { size: '1-1/2"' },
          { size: '2"' },
          { size: '3"' },
        ],
      },
      {
        name: "PVC Pipe Clip",
        slug: "pvc-pipe-clip",
        image: "/images/products/pvc-pipe-clip.jpg",
        preview: "PVC pipe clip for securing and supporting pipes along walls and structures.",
        description: "PVC pipe clip (pipe clamp / saddle clamp) is used to support, guide, and secure PVC pipes to walls, ceilings, or structural supports. Available in single and double clip styles with pre-drilled mounting holes. Resistant to corrosion and UV degradation.",
        specs: [
          { key: "material", value: "PVC" },
          { key: "color", value: "Gray" },
          { key: "size", value: "Fits pipe OD 20mm - 160mm" },
          { key: "mounting", value: "Single screw or double screw" },
          { key: "application", value: "Pipe support and fixing on walls, ceilings, and structures" },
        ],
        tables: [
          { pipe_od_mm: "20", pipe_size: '1/2"' },
          { pipe_od_mm: "25", pipe_size: '3/4"' },
          { pipe_od_mm: "32", pipe_size: '1"' },
          { pipe_od_mm: "40", pipe_size: '1-1/4"' },
          { pipe_od_mm: "50", pipe_size: '1-1/2"' },
          { pipe_od_mm: "63", pipe_size: '2"' },
          { pipe_od_mm: "90", pipe_size: '3"' },
          { pipe_od_mm: "110", pipe_size: '4"' },
          { pipe_od_mm: "160", pipe_size: '6"' },
        ],
      },
      {
        name: "PVC SCH80 Cross Tee",
        slug: "sch80-pvc-cross-tee",
        image: "/images/products/sch80-pvc-cross-tee.jpg",
        preview: "SCH 80 PVC cross tee for four-way pipe connections in a single fitting.",
        description: "SCH 80 PVC cross tee (4-way tee) provides four equal-size socket outlets in a cross configuration, allowing flow to be split or combined from four directions. Manufactured to ASTM D 2467 standard. Used in complex industrial and chemical pipeline layouts requiring four-way branching.",
        specs: [
          { key: "material", value: "PVC / UPVC" },
          { key: "color", value: "Gray" },
          { key: "standard", value: "ASTM D 2467, SCH 80" },
          { key: "size", value: '1/2" - 4"' },
          { key: "connection", value: "Socket x Socket x Socket x Socket (Solvent Weld)" },
          { key: "pressure_rating", value: "SCH 80" },
          { key: "working_temperature", value: "Up to 60°C" },
          { key: "application", value: "Four-way pipeline branching, chemical distribution, industrial manifolds" },
        ],
        tables: [
          { size: '1/2"', weight_kg: "0.09" },
          { size: '3/4"', weight_kg: "0.14" },
          { size: '1"', weight_kg: "0.22" },
          { size: '1-1/4"', weight_kg: "0.38" },
          { size: '1-1/2"', weight_kg: "0.52" },
          { size: '2"', weight_kg: "0.85" },
          { size: '3"', weight_kg: "2.10" },
          { size: '4"', weight_kg: "3.80" },
        ],
      },
      {
        name: "PVC SCH80 One Sided Female Tee",
        slug: "sch80-pvc-one-sided-female-tee",
        image: "/images/products/sch80-pvc-one-sided-female-tee.jpg",
        preview: "SCH 80 PVC tee with two socket ends and one female NPT branch outlet.",
        description: "SCH 80 PVC one sided female tee (female branch tee) features two socket ends for the main run and one female NPT threaded branch outlet. Allows a threaded connection on the branch without requiring a separate adaptor. Manufactured to ASTM D 2467 standard for high-pressure industrial and chemical piping.",
        specs: [
          { key: "material", value: "PVC / UPVC" },
          { key: "color", value: "Gray" },
          { key: "standard", value: "ASTM D 2467, SCH 80" },
          { key: "thread_standard", value: "NPT Female Branch (ANSI/ASME B1.20.1)" },
          { key: "size", value: '1/2" - 3" run; 1/4" - 2" branch' },
          { key: "connection", value: "Socket x Socket x NPT Female Thread" },
          { key: "pressure_rating", value: "SCH 80" },
          { key: "working_temperature", value: "Up to 60°C" },
          { key: "application", value: "Branch connection to threaded instruments, valves, and gauges" },
        ],
        tables: [
          { run_size: '1/2"', branch_npt: '1/2" Female' },
          { run_size: '3/4"', branch_npt: '3/4" Female' },
          { run_size: '1"', branch_npt: '1" Female' },
          { run_size: '1-1/4"', branch_npt: '1" Female' },
          { run_size: '1-1/2"', branch_npt: '1-1/2" Female' },
          { run_size: '2"', branch_npt: '2" Female' },
          { run_size: '3"', branch_npt: '2" Female' },
        ],
      },
    ],
  },
  {
    name: "BS Standard Female Threaded Fittings",
    slug: "bs-standard-female-threaded-fittings",
    products: [
      {
        name: "PVC Double Female Socket (BS Standard)",
        slug: "bs-pvc-double-female-socket",
        image: "/images/products/bs-pvc-double-female-socket.jpg",
        preview: "BS standard PVC double female socket for joining two male-threaded pipes or fittings.",
        description: "BS standard PVC double female socket (female coupling F/F) connects two male BSPT threaded pipes or fittings in a straight run. Manufactured to BS EN 10226-2 / BS-21 standard in Gray PVC. Suitable for cold water supply, irrigation, and general plumbing applications. Resistant to corrosion and a wide range of chemicals.",
        specs: [
          { key: "material", value: "PVC / UPVC" },
          { key: "color", value: "Gray" },
          { key: "standard", value: "BS EN 10226-2 / BS-21" },
          { key: "thread_standard", value: "BSPT (BS-21)" },
          { key: "size", value: "20mm - 63mm" },
          { key: "connection", value: "BSPT Female Thread x BSPT Female Thread" },
          { key: "working_temperature", value: "Up to 60°C" },
          { key: "application", value: "Cold water supply, plumbing, irrigation, general piping" },
        ],
        tables: [
          { nom_size: "20", D_mm: "27.5", d_mm: "20", L_mm: "16.6", H_mm: "35.7" },
          { nom_size: "25", D_mm: "33.3", d_mm: "25", L_mm: "19.5", H_mm: "42" },
          { nom_size: "32", D_mm: "40.5", d_mm: "32", L_mm: "22.5", H_mm: "48" },
          { nom_size: "50", D_mm: "58.3", d_mm: "50.4", L_mm: "33.5", H_mm: "70" },
          { nom_size: "63", D_mm: "75", d_mm: "63", L_mm: "38.5", H_mm: "80" },
        ],
      },
      {
        name: "PVC Reducing Female Threaded Socket TxT (BS Standard)",
        slug: "bs-pvc-reducing-female-socket",
        image: "/images/products/bs-pvc-reducing-female-socket.jpg",
        preview: "BS standard PVC reducing female socket to connect two different BSPT thread sizes.",
        description: "BS standard PVC reducing female threaded socket (female reducing coupling F/F) connects two male BSPT threaded pipes or fittings of different sizes in a straight run. Manufactured to BS EN 10226-2 / BS-21 standard. Used where a pipe size reduction is required in threaded plumbing, water supply, and irrigation systems.",
        specs: [
          { key: "material", value: "PVC / UPVC" },
          { key: "color", value: "Gray" },
          { key: "standard", value: "BS EN 10226-2 / BS-21" },
          { key: "thread_standard", value: "BSPT (BS-21)" },
          { key: "size", value: '1-1/2"' },
          { key: "connection", value: "BSPT Female Thread (large) x BSPT Female Thread (small)" },
          { key: "working_temperature", value: "Up to 60°C" },
          { key: "application", value: "Pipe size reduction, cold water supply, plumbing, irrigation" },
        ],
        tables: [
          { nom_size: '1 1/2"', D_mm: "48", d_mm: "43.3", D1_mm: "53.3", thread: 'RP1 1/2"', I_mm: "29", L1_mm: "23.5", L_mm: "54" },
        ],
      },
      {
        name: "PVC Three Side Threaded Female Tee (BS Standard)",
        slug: "bs-pvc-female-tee",
        image: "/images/products/bs-pvc-female-tee.jpg",
        preview: "BS standard PVC female tee with BSPT female threads on all three outlets.",
        description: "BS standard PVC three-side threaded female tee (female tee F/F/F) provides a T-shaped branch connection with BSPT female threads on all three outlets. Manufactured to BS EN 10226-2 / BS-21 standard. Used for branching threaded piping systems in cold water supply, plumbing, and irrigation applications.",
        specs: [
          { key: "material", value: "PVC / UPVC" },
          { key: "color", value: "Gray" },
          { key: "standard", value: "BS EN 10226-2 / BS-21" },
          { key: "thread_standard", value: "BSPT (BS-21)" },
          { key: "size", value: '1/2" - 1-1/4"' },
          { key: "connection", value: "BSPT Female Thread x BSPT Female Thread x BSPT Female Thread" },
          { key: "working_temperature", value: "Up to 60°C" },
          { key: "application", value: "Pipeline branching, cold water supply, irrigation, general plumbing" },
        ],
        tables: [
          { nom_size: '1/2"', D1_mm: "33.2", D_mm: "20", d_mm: "15.9", I_mm: "13", G: '1/2"', L_mm: "52", H_mm: "39" },
          { nom_size: '3/4" x 1/2"', D1_mm: "33.2", D_mm: "26.8", d_mm: "22.2", I_mm: "18", G: '1/2"', L_mm: "68.5", H_mm: "31.5" },
          { nom_size: '1" x 1/2"', D1_mm: "34.9", D_mm: "34.5", d_mm: "28.6", I_mm: "23", G: '1/2"', L_mm: "80", H_mm: "35" },
          { nom_size: '1-1/4"', D1_mm: "59.5", D_mm: "41.8", d_mm: "35.2", I_mm: "28.1", G: '1 1/4"', L_mm: "94.8", H_mm: "45.9" },
          { nom_size: '1-1/4" x 1/2"', D1_mm: "33.2", D_mm: "41.8", d_mm: "35.2", I_mm: "28.1", G: '1/2"', L_mm: "94.8", H_mm: "40" },
        ],
      },
      {
        name: "PVC Double Threaded Female Elbow 90° (BS Standard)",
        slug: "bs-pvc-double-female-elbow",
        image: "/images/products/bs-pvc-double-female-elbow.jpg",
        preview: "BS standard PVC 90° elbow with BSPT female threads on both ends.",
        description: "BS standard PVC double threaded female elbow (female elbow F/F) provides a 90° directional change with BSPT female threads on both ends. Manufactured to BS EN 10226-2 / BS-21 standard. Used to connect two male-threaded pipes or fittings at right angles in cold water supply, irrigation, and plumbing systems.",
        specs: [
          { key: "material", value: "PVC / UPVC" },
          { key: "color", value: "Gray" },
          { key: "standard", value: "BS EN 10226-2 / BS-21" },
          { key: "thread_standard", value: "BSPT (BS-21)" },
          { key: "angle", value: "90°" },
          { key: "size", value: '32mm x 1"' },
          { key: "connection", value: "BSPT Female Thread x BSPT Female Thread" },
          { key: "working_temperature", value: "Up to 60°C" },
          { key: "application", value: "Pipe direction changes, cold water supply, irrigation, plumbing" },
        ],
        tables: [
          { nom_size: '32 x 1"', D_mm: "41", d_mm: "32", G: '1"', L_mm: "22.5" },
        ],
      },
    ],
  },
  {
    name: "PVC Valve",
    slug: "pvc-valve",
    products: [
      {
        name: "PVC Sampling Valve",
        slug: "pvc-sampling-valve",
        image: "/images/products/pvc-sampling-valve.jpg",
        preview: "PVC sampling valve for drawing fluid samples from pipelines without shutting down the system.",
        description: "PVC sampling valve is a quarter-turn plug-type valve designed for extracting fluid samples from pipelines or tanks in chemical processing, water treatment, and laboratory applications. It provides a leak-free seal when closed and a controlled sample flow when opened. Manufactured from high-quality UPVC for excellent chemical resistance and long service life.",
        specs: [
          { key: "material", value: "PVC / UPVC" },
          { key: "color", value: "Black" },
          { key: "standard", value: "ISO 727" },
          { key: "size", value: '1/2" - 2"' },
          { key: "connection", value: "Socket (Solvent Weld) or NPT Thread" },
          { key: "seal", value: "EPDM / FKM (Viton)" },
          { key: "pressure_rating", value: "PN10 (up to 1.0 MPa)" },
          { key: "working_temperature", value: "Up to 60°C" },
          { key: "application", value: "Fluid sampling, chemical plants, water treatment, laboratory lines" },
        ],
        tables: [
          { size: '1/2"', od_mm: "21.3" },
          { size: '3/4"', od_mm: "26.7" },
          { size: '1"', od_mm: "33.4" },
          { size: '1-1/4"', od_mm: "42.2" },
          { size: '1-1/2"', od_mm: "48.3" },
          { size: '2"', od_mm: "60.3" },
        ],
      },
      {
        name: "PVC General Handle Butterfly Valve ASTM Standard",
        slug: "pvc-butterfly-valve-astm",
        image: "/images/products/pvc-butterfly-valve-astm.jpg",
        preview: "ASTM standard PVC butterfly valve with general lever handle for flow control in large pipe systems.",
        description: "PVC general handle butterfly valve (ASTM standard) is a quarter-turn wafer-style valve used to regulate or isolate flow in large-diameter pipe systems. The disc rotates 90° to fully open or close. Manufactured to ASTM standards with a PVC body and disc, EPDM seat, and stainless steel stem. Ideal for water treatment, irrigation, chemical processing, and industrial pipelines.",
        specs: [
          { key: "material", value: "PVC body and disc, stainless steel stem" },
          { key: "color", value: "Gray" },
          { key: "standard", value: "ASTM" },
          { key: "size", value: '2" - 12" (DN50 - DN300)' },
          { key: "connection", value: "Wafer (flange-mounted between flanges)" },
          { key: "seat_material", value: "EPDM / NBR" },
          { key: "actuator", value: "General lever handle (lockable)" },
          { key: "pressure_rating", value: "PN10 (150 PSI)" },
          { key: "working_temperature", value: "Up to 60°C" },
          { key: "application", value: "Water treatment, chemical lines, irrigation systems, industrial pipelines" },
        ],
        tables: [
          { size: '2"', dn: "DN50" },
          { size: '2-1/2"', dn: "DN65" },
          { size: '3"', dn: "DN80" },
          { size: '4"', dn: "DN100" },
          { size: '5"', dn: "DN125" },
          { size: '6"', dn: "DN150" },
          { size: '8"', dn: "DN200" },
          { size: '10"', dn: "DN250" },
          { size: '12"', dn: "DN300" },
        ],
      },
      {
        name: "PVC Compact Ball Valve",
        slug: "pvc-compact-ball-valve",
        image: "/images/products/pvc-compact-ball-valve.jpg",
        preview: "PVC compact ball valve for on/off flow control in tight-space piping applications.",
        description: "PVC compact ball valve is a space-saving quarter-turn ball valve with socket or threaded ends. It features a full-bore PVC ball, PTFE seats, and EPDM O-ring seals for reliable shut-off in chemical, water supply, and industrial piping systems. Its compact design makes it ideal for installations with limited space.",
        specs: [
          { key: "material", value: "PVC / UPVC body, PVC ball, PTFE seats" },
          { key: "color", value: "Gray" },
          { key: "standard", value: "ISO 727 / DIN" },
          { key: "size", value: '1/4" - 2" (DN8 - DN50)' },
          { key: "connection", value: "Socket (Solvent Weld) or NPT/BSP Thread" },
          { key: "seal", value: "PTFE seats, EPDM O-rings" },
          { key: "pressure_rating", value: "PN10 - PN16" },
          { key: "working_temperature", value: "Up to 60°C" },
          { key: "application", value: "Chemical processing, water treatment, irrigation, general industrial use" },
        ],
        tables: [
          { size: '1/4"', dn: "DN8" },
          { size: '3/8"', dn: "DN10" },
          { size: '1/2"', dn: "DN15" },
          { size: '3/4"', dn: "DN20" },
          { size: '1"', dn: "DN25" },
          { size: '1-1/4"', dn: "DN32" },
          { size: '1-1/2"', dn: "DN40" },
          { size: '2"', dn: "DN50" },
        ],
      },
      {
        name: "PVC Threaded Ball Valve Standard",
        slug: "pvc-threaded-ball-valve",
        image: "/images/products/pvc-threaded-ball-valve.jpg",
        preview: "PVC ball valve with male or female NPT/BSP threads for easy threaded pipe installation.",
        description: "PVC threaded ball valve provides quarter-turn on/off flow control with NPT or BSP threaded ends for direct connection to threaded pipes or fittings. Features a full-bore PVC ball, PTFE seats, and lever handle. Manufactured from UPVC for high chemical resistance. Suitable for water supply, irrigation, and chemical distribution systems.",
        specs: [
          { key: "material", value: "PVC / UPVC body and ball, PTFE seats" },
          { key: "color", value: "Gray" },
          { key: "standard", value: "ISO 727" },
          { key: "thread_standard", value: "NPT or BSP" },
          { key: "size", value: '1/4" - 4" (DN8 - DN100)' },
          { key: "connection", value: "NPT Female Thread x NPT Female Thread (or BSP)" },
          { key: "seal", value: "PTFE seats, EPDM O-rings" },
          { key: "pressure_rating", value: "PN10 - PN16" },
          { key: "working_temperature", value: "Up to 60°C" },
          { key: "application", value: "Water supply, irrigation, chemical lines, industrial pipelines" },
        ],
        tables: [
          { size: '1/4"', dn: "DN8" },
          { size: '3/8"', dn: "DN10" },
          { size: '1/2"', dn: "DN15" },
          { size: '3/4"', dn: "DN20" },
          { size: '1"', dn: "DN25" },
          { size: '1-1/4"', dn: "DN32" },
          { size: '1-1/2"', dn: "DN40" },
          { size: '2"', dn: "DN50" },
          { size: '3"', dn: "DN80" },
          { size: '4"', dn: "DN100" },
        ],
      },
      {
        name: "PVC True Union Ball Valve",
        slug: "pvc-true-union-ball-valve",
        image: "/images/products/pvc-true-union-ball-valve.jpg",
        preview: "PVC true union ball valve for in-line removal and maintenance without disturbing pipework.",
        description: "PVC true union ball valve features a two-piece union body construction that allows the valve to be removed from the pipeline for inspection or replacement without cutting the pipe. It offers a full-bore flow path, PTFE seats, EPDM seals, and a lever handle. Available in socket or threaded end connections. Ideal for systems requiring periodic maintenance.",
        specs: [
          { key: "material", value: "PVC / UPVC body and ball, PTFE seats" },
          { key: "color", value: "Gray" },
          { key: "standard", value: "ASTM F1970 / ISO 727" },
          { key: "size", value: '1/2" - 4" (DN15 - DN100)' },
          { key: "connection", value: "Socket (Solvent Weld) or NPT/BSP Thread (union ends)" },
          { key: "seal", value: "PTFE seats, EPDM O-rings" },
          { key: "pressure_rating", value: "PN10 - PN16" },
          { key: "working_temperature", value: "Up to 60°C" },
          { key: "application", value: "Chemical processing, water treatment, industrial systems requiring in-line serviceability" },
        ],
        tables: [
          { size: '1/2"', dn: "DN15" },
          { size: '3/4"', dn: "DN20" },
          { size: '1"', dn: "DN25" },
          { size: '1-1/4"', dn: "DN32" },
          { size: '1-1/2"', dn: "DN40" },
          { size: '2"', dn: "DN50" },
          { size: '3"', dn: "DN80" },
          { size: '4"', dn: "DN100" },
        ],
      },
      {
        name: "PVC Foot Valve",
        slug: "pvc-foot-valve",
        image: "/images/products/pvc-foot-valve.jpg",
        preview: "PVC foot valve installed at pump inlet to maintain prime and prevent backflow.",
        description: "PVC foot valve is a spring-loaded non-return valve installed at the bottom of a suction pipe to keep the pump primed and prevent backflow when the pump stops. It features a built-in strainer screen to protect the pump from debris. Manufactured from UPVC with EPDM seals for chemical resistance and long service life.",
        specs: [
          { key: "material", value: "PVC / UPVC body, stainless steel spring, EPDM disc" },
          { key: "color", value: "Gray" },
          { key: "standard", value: "ISO 727" },
          { key: "size", value: '1/2" - 6" (DN15 - DN150)' },
          { key: "connection", value: "NPT Female Thread or Socket (Solvent Weld)" },
          { key: "seal", value: "EPDM disc, NBR O-ring" },
          { key: "pressure_rating", value: "PN10" },
          { key: "working_temperature", value: "Up to 60°C" },
          { key: "application", value: "Pump suction lines, wells, sumps, water supply, irrigation systems" },
        ],
        tables: [
          { size: '1/2"', dn: "DN15" },
          { size: '3/4"', dn: "DN20" },
          { size: '1"', dn: "DN25" },
          { size: '1-1/4"', dn: "DN32" },
          { size: '1-1/2"', dn: "DN40" },
          { size: '2"', dn: "DN50" },
          { size: '3"', dn: "DN80" },
          { size: '4"', dn: "DN100" },
          { size: '6"', dn: "DN150" },
        ],
      },
      {
        name: "PVC Double Union Ball Check Valve",
        slug: "pvc-double-union-ball-check-valve",
        image: "/images/products/pvc-double-union-ball-check-valve.jpg",
        preview: "PVC double union ball check valve to prevent backflow with easy in-line removal.",
        description: "PVC double union ball check valve uses a free-floating PVC ball to prevent reverse flow in piping systems. The double union design allows the valve body to be removed from the pipeline without cutting pipe, making it easy to inspect or replace the ball. Suitable for chemical dosing lines, water treatment, and pump discharge applications.",
        specs: [
          { key: "material", value: "PVC / UPVC body, PVC ball, EPDM seals" },
          { key: "color", value: "Gray" },
          { key: "standard", value: "ISO 727 / ASTM" },
          { key: "size", value: '1/2" - 4" (DN15 - DN100)' },
          { key: "connection", value: "Socket (Solvent Weld) or NPT/BSP Thread (union ends)" },
          { key: "seal", value: "EPDM O-rings" },
          { key: "pressure_rating", value: "PN10" },
          { key: "working_temperature", value: "Up to 60°C" },
          { key: "application", value: "Pump discharge lines, chemical dosing, water treatment, backflow prevention" },
        ],
        tables: [
          { size: '1/2"', dn: "DN15" },
          { size: '3/4"', dn: "DN20" },
          { size: '1"', dn: "DN25" },
          { size: '1-1/4"', dn: "DN32" },
          { size: '1-1/2"', dn: "DN40" },
          { size: '2"', dn: "DN50" },
          { size: '3"', dn: "DN80" },
          { size: '4"', dn: "DN100" },
        ],
      },
      {
        name: "PVC Swing Check Valve",
        slug: "pvc-swing-check-valve",
        image: "/images/products/pvc-swing-check-valve.jpg",
        preview: "PVC swing check valve allowing flow in one direction with gravity-assisted closure.",
        description: "PVC swing check valve uses a hinged disc (clapper) that swings open under forward flow and closes by gravity when flow stops or reverses. It is designed for horizontal or vertical pipeline installation and provides reliable backflow prevention with low pressure drop. Manufactured from UPVC with EPDM seals for chemical and corrosion resistance.",
        specs: [
          { key: "material", value: "PVC / UPVC body, PVC disc, stainless steel hinge pin" },
          { key: "color", value: "Gray" },
          { key: "standard", value: "ISO 727 / BS 5153" },
          { key: "size", value: '1/2" - 6" (DN15 - DN150)' },
          { key: "connection", value: "Socket (Solvent Weld) or Flanged" },
          { key: "seal", value: "EPDM" },
          { key: "pressure_rating", value: "PN10" },
          { key: "working_temperature", value: "Up to 60°C" },
          { key: "application", value: "Water supply, irrigation, pump discharge, chemical pipelines" },
        ],
        tables: [
          { size: '1/2"', dn: "DN15" },
          { size: '3/4"', dn: "DN20" },
          { size: '1"', dn: "DN25" },
          { size: '1-1/2"', dn: "DN40" },
          { size: '2"', dn: "DN50" },
          { size: '3"', dn: "DN80" },
          { size: '4"', dn: "DN100" },
          { size: '6"', dn: "DN150" },
        ],
      },
      {
        name: "PVC Wafer Check Valve",
        slug: "pvc-wafer-check-valve",
        image: "/images/products/pvc-wafer-check-valve.jpg",
        preview: "PVC wafer check valve with dual-plate spring-assisted closure for compact in-line backflow prevention.",
        description: "PVC wafer check valve is a slim, lightweight dual-plate (dual-disc) check valve designed to fit between pipe flanges. Spring-assisted discs open under forward flow and close instantly when flow stops, minimizing water hammer. Its wafer body design reduces installation space and weight compared to full-body check valves.",
        specs: [
          { key: "material", value: "PVC / UPVC body, PVC discs, stainless steel spring and hinge pin" },
          { key: "color", value: "Gray" },
          { key: "standard", value: "API 594 / ISO 13709" },
          { key: "size", value: '2" - 12" (DN50 - DN300)' },
          { key: "connection", value: "Wafer (mounted between flanges, ANSI 150 / PN10 - PN16)" },
          { key: "seal", value: "EPDM / NBR" },
          { key: "pressure_rating", value: "PN10 - PN16" },
          { key: "working_temperature", value: "Up to 60°C" },
          { key: "application", value: "Water treatment plants, pump stations, industrial and chemical pipelines" },
        ],
        tables: [
          { size: '2"', dn: "DN50" },
          { size: '3"', dn: "DN80" },
          { size: '4"', dn: "DN100" },
          { size: '6"', dn: "DN150" },
          { size: '8"', dn: "DN200" },
          { size: '10"', dn: "DN250" },
          { size: '12"', dn: "DN300" },
        ],
      },
      {
        name: "PVC Air Relief Valve 1 Inch",
        slug: "pvc-air-relief-valve-1inch",
        image: "/images/products/pvc-air-relief-valve-1inch.jpg",
        preview: "1 inch PVC air relief valve to automatically release trapped air from pressurized pipelines.",
        description: "PVC air relief valve (1 inch) automatically vents trapped air from pressurized water pipelines to prevent air locks and maintain efficient flow. The float-operated mechanism opens to release air and closes when water fills the chamber. Manufactured from UPVC with stainless steel float for long service life.",
        specs: [
          { key: "material", value: "PVC / UPVC body, stainless steel float" },
          { key: "color", value: "Blue and black" },
          { key: "size", value: '1" (DN25)' },
          { key: "connection", value: "NPT Male Thread or Flanged" },
          { key: "seal", value: "EPDM" },
          { key: "pressure_rating", value: "PN10 (up to 10 bar)" },
          { key: "working_temperature", value: "Up to 60°C" },
          { key: "application", value: "Water mains, irrigation pipelines, pump discharge, industrial water systems" },
        ],
        tables: [
          { size: '1"', dn: "DN25", max_pressure_bar: "10", connection: '1" NPT Male' },
        ],
      },
      {
        name: "PVC Air Relief Valve 2 Inch",
        slug: "pvc-air-relief-valve-2inch",
        image: "/images/products/pvc-air-relief-valve-2inch.jpg",
        preview: "2 inch PVC air relief valve for high-capacity air venting in large water pipelines.",
        description: "PVC air relief valve (2 inch) provides high-capacity automatic air venting for larger-diameter pressurized water pipelines. It uses a float mechanism to release accumulated air pockets and re-seals when the chamber fills with water.",
        specs: [
          { key: "material", value: "PVC / UPVC body, stainless steel float" },
          { key: "color", value: "Blue and black" },
          { key: "size", value: '2" (DN50)' },
          { key: "connection", value: "NPT Male Thread or Flanged" },
          { key: "seal", value: "EPDM" },
          { key: "pressure_rating", value: "PN10 (up to 10 bar)" },
          { key: "working_temperature", value: "Up to 60°C" },
          { key: "application", value: "Large water mains, municipal pipelines, pump discharge, irrigation systems" },
        ],
        tables: [
          { size: '2"', dn: "DN50", max_pressure_bar: "10", connection: '2" NPT Male' },
        ],
      },
      {
        name: "PVC (NRV) No Return Valve 6 Inch",
        slug: "pvc-nrv-6inch",
        image: "/images/products/pvc-nrv-6inch.jpg",
        preview: "6 inch PVC non-return valve (NRV) for large-bore backflow prevention in water and industrial systems.",
        description: "PVC no-return valve (NRV) 6 inch is a large-bore check valve that allows flow in one direction only and prevents reverse flow when the pump stops or pressure drops. Manufactured from UPVC for excellent chemical and UV resistance.",
        specs: [
          { key: "material", value: "PVC / UPVC body, PVC or rubber-lined disc" },
          { key: "color", value: "Gray" },
          { key: "standard", value: "ISO 727 / BS 5153" },
          { key: "size", value: '6" (DN150)' },
          { key: "connection", value: "Flanged (ANSI 150 / PN10) or Socket (Solvent Weld)" },
          { key: "seal", value: "EPDM / NBR" },
          { key: "pressure_rating", value: "PN10" },
          { key: "working_temperature", value: "Up to 60°C" },
          { key: "application", value: "Municipal water, pump stations, sewage systems, large industrial pipelines" },
        ],
        tables: [
          { size: '6"', dn: "DN150", flange_standard: "ANSI 150 / PN10", pressure_rating_bar: "10" },
        ],
      },
    ],
  },
  {
    name: "PVC Strainer",
    slug: "pvc-strainer",
    products: [
      {
        name: "PVC Y-Strainer",
        slug: "pvc-y-strainer",
        image: "/images/products/pvc-y-strainer.jpg",
        preview: "PVC Y-strainer to filter debris and particulates from piping systems protecting pumps and equipment.",
        description: "PVC Y-strainer removes solid particles, debris, and sediment from liquid pipelines to protect downstream equipment such as pumps, meters, valves, and nozzles. The Y-shaped body houses a removable stainless steel mesh screen basket that can be cleaned or replaced without removing the valve body from the pipeline. Manufactured from UPVC with excellent chemical resistance.",
        specs: [
          { key: "material", value: "PVC / UPVC body, stainless steel screen (mesh 40 - 80 mesh)" },
          { key: "color", value: "Dark blue and Black" },
          { key: "standard", value: "ISO 727" },
          { key: "size", value: '1/2" - 4" (DN15 - DN100)' },
          { key: "connection", value: "Socket (Solvent Weld) or NPT/BSP Thread or Flanged" },
          { key: "screen_mesh", value: "20 mesh, 40 mesh, 80 mesh (customizable)" },
          { key: "pressure_rating", value: "PN10 - PN16" },
          { key: "working_temperature", value: "Up to 60°C" },
          { key: "application", value: "Pump inlet protection, water treatment, irrigation, chemical processing, industrial pipelines" },
        ],
        tables: [
          { size: '1/2"', dn: "DN15", screen_area_cm2: "8" },
          { size: '3/4"', dn: "DN20", screen_area_cm2: "12" },
          { size: '1"', dn: "DN25", screen_area_cm2: "18" },
          { size: '1-1/4"', dn: "DN32", screen_area_cm2: "26" },
          { size: '1-1/2"', dn: "DN40", screen_area_cm2: "35" },
          { size: '2"', dn: "DN50", screen_area_cm2: "55" },
          { size: '3"', dn: "DN80", screen_area_cm2: "120" },
          { size: '4"', dn: "DN100", screen_area_cm2: "195" },
        ],
      },
    ],
  },
  {
    name: "PVC Disc Filter",
    slug: "pvc-disc-filter",
    products: [
      {
        name: "PVC Disc Filter",
        slug: "pvc-disc-filter",
        image: "/images/products/pvc-disc-filter.jpg",
        images: [
          "/images/products/pvc-disc-filter.jpg",
          "/images/products/pvc-disc-filter-2.jpg",
        ],
        preview: "PVC disc filter using stacked grooved discs for fine filtration in irrigation and water treatment systems.",
        description: "PVC disc filter is a high-efficiency filtration device that uses a stack of grooved PVC or polypropylene discs compressed together to form a three-dimensional filtration matrix. Water passes through the inter-disc channels, and particles larger than the filter rating are captured on the disc surfaces. The disc stack can be flushed clean by backwashing. Available in various micron ratings and suited for drip irrigation, municipal water supply, and industrial water treatment.",
        specs: [
          { key: "material", value: "PVC / UPVC housing, polypropylene disc stack" },
          { key: "color", value: "Black" },
          { key: "size", value: '3/4" - 3" inlet/outlet (DN20 - DN80)' },
          { key: "filtration_rating", value: "20 micron, 55 micron, 100 micron, 130 micron, 200 micron (color-coded discs)" },
          { key: "connection", value: "NPT Female Thread or Flanged" },
          { key: "pressure_rating", value: "PN8 - PN10 (up to 10 bar)" },
          { key: "flow_rate", value: "Up to 30 m³/h depending on size and rating" },
          { key: "working_temperature", value: "Up to 50°C" },
          { key: "backwash", value: "Manual or automatic backwash" },
          { key: "application", value: "Drip irrigation, micro-irrigation, municipal water filtration, industrial water treatment, cooling towers" },
        ],
        tables: [
          { size: '3/4"', dn: "DN20", flow_rate_m3h: "4", micron_options: "20, 55, 100, 130, 200" },
          { size: '1"', dn: "DN25", flow_rate_m3h: "7", micron_options: "20, 55, 100, 130, 200" },
          { size: '1-1/2"', dn: "DN40", flow_rate_m3h: "15", micron_options: "20, 55, 100, 130, 200" },
          { size: '2"', dn: "DN50", flow_rate_m3h: "20", micron_options: "20, 55, 100, 130, 200" },
          { size: '3"', dn: "DN80", flow_rate_m3h: "30", micron_options: "55, 100, 130, 200" },
        ],
      },
    ],
  },
  {
    name: "PVC Pipes",
    slug: "pvc-pipes",
    products: [
      {
        name: "PVC Pipe SCH 80",
        slug: "sch80-pvc-pipe",
        image: "/images/products/sch80-pvc-pipe.jpg",
        preview: "SCH 80 gray PVC pipe manufactured to ASTM D1785 standard for high-pressure industrial and chemical piping systems.",
        description: 'SCH 80 PVC pipe is manufactured to ASTM D1785 standard using Polyvinyl Chloride (PVC/UPVC) material. Featuring thicker walls than SCH 40, it is designed for high-pressure applications in industrial, chemical processing, and water treatment systems. Available in sizes from 1/2" to 16" with socket, rubber ring, or plain end connections. Certified by SGS, NSF, ISO, and COC with a 50-year warranty.',
        specs: [
          { key: "material", value: "PVC / UPVC (Polyvinyl Chloride)" },
          { key: "color", value: "Gray (white or customized available)" },
          { key: "standard", value: "ASTM D1785, SCH 80" },
          { key: "size", value: '1/2" - 16"' },
          { key: "connection", value: "Socket, Rubber Ring, Plain End" },
          { key: "pressure_rating", value: "SCH 80 (varies by size and wall thickness)" },
          { key: "working_temperature", value: "Up to 60°C" },
          { key: "vicat_softening_temp", value: "≥80°C" },
          { key: "density", value: "1330–1460 kg/m³" },
          { key: "warranty", value: "50 years" },
          { key: "certifications", value: "SGS, NSF, ISO, COC" },
          { key: "application", value: "Industrial piping, chemical processing, water treatment, irrigation systems" },
        ],
        tables: [
          { size: '1/2"', od_mm: "21.34", wall_thickness_mm: "3.73", tolerance_mm: "0~+0.51" },
          { size: '3/4"', od_mm: "26.67", wall_thickness_mm: "3.91", tolerance_mm: "0~+0.51" },
          { size: '1"', od_mm: "33.40", wall_thickness_mm: "4.55", tolerance_mm: "0~+0.53" },
          { size: '1-1/4"', od_mm: "42.16", wall_thickness_mm: "4.85", tolerance_mm: "0~+0.58" },
          { size: '1-1/2"', od_mm: "48.26", wall_thickness_mm: "5.08", tolerance_mm: "0~+0.61" },
          { size: '2"', od_mm: "60.32", wall_thickness_mm: "5.54", tolerance_mm: "0~+0.66" },
          { size: '2-1/2"', od_mm: "73.02", wall_thickness_mm: "7.01", tolerance_mm: "0~+0.84" },
          { size: '3"', od_mm: "88.90", wall_thickness_mm: "7.62", tolerance_mm: "0~+0.91" },
          { size: '4"', od_mm: "114.30", wall_thickness_mm: "8.56", tolerance_mm: "0~+1.02" },
          { size: '5"', od_mm: "141.30", wall_thickness_mm: "9.52", tolerance_mm: "0~+1.14" },
          { size: '6"', od_mm: "168.28", wall_thickness_mm: "10.97", tolerance_mm: "0~+1.32" },
          { size: '8"', od_mm: "219.08", wall_thickness_mm: "12.70", tolerance_mm: "0~+1.52" },
          { size: '10"', od_mm: "273.05", wall_thickness_mm: "15.06", tolerance_mm: "0~+1.80" },
          { size: '12"', od_mm: "323.85", wall_thickness_mm: "17.45", tolerance_mm: "0~+2.08" },
          { size: '14"', od_mm: "355.60", wall_thickness_mm: "19.05", tolerance_mm: "0~+2.29" },
          { size: '16"', od_mm: "406.40", wall_thickness_mm: "21.41", tolerance_mm: "0~+2.57" },
        ],
      },
      {
        name: "PVC Pipe SCH 40",
        slug: "sch40-pvc-pipe",
        image: "/images/products/sch40-pvc-pipe.jpg",
        preview: "SCH 40 PVC pipe to ASTM D1785 standard for water supply, irrigation, and general industrial applications.",
        description: 'SCH 40 PVC pipe is manufactured to ASTM D1785 standard using PVC/UPVC material. It is the most widely used schedule for general-purpose water supply, irrigation, drainage, and light industrial piping. Available in sizes from 1/2" to 24" with socket connections.',
        specs: [
          { key: "material", value: "PVC / UPVC (Polyvinyl Chloride)" },
          { key: "color", value: "Gray" },
          { key: "standard", value: "ASTM D1785, SCH 40" },
          { key: "size", value: '1/2" - 24"' },
          { key: "connection", value: "Socket" },
          { key: "pressure_rating", value: "SCH 40 (varies by size and wall thickness)" },
          { key: "working_temperature", value: "Up to 60°C" },
          { key: "vicat_softening_temp", value: "≥80°C" },
          { key: "density", value: "1330–1460 kg/m³" },
          { key: "warranty", value: "50 years" },
          { key: "certifications", value: "SGS, NSF, ISO, COC" },
          { key: "application", value: "Water supply, irrigation, drainage, general industrial and agricultural piping" },
        ],
        tables: [
          { size: '1/2"', od_mm: "21.34", wall_thickness_mm: "2.77", tolerance_mm: "0~+0.51" },
          { size: '3/4"', od_mm: "26.67", wall_thickness_mm: "2.87", tolerance_mm: "0~+0.51" },
          { size: '1"', od_mm: "33.40", wall_thickness_mm: "3.38", tolerance_mm: "0~+0.51" },
          { size: '1-1/4"', od_mm: "42.16", wall_thickness_mm: "3.56", tolerance_mm: "0~+0.51" },
          { size: '1-1/2"', od_mm: "48.26", wall_thickness_mm: "3.68", tolerance_mm: "0~+0.51" },
          { size: '2"', od_mm: "60.32", wall_thickness_mm: "3.91", tolerance_mm: "0~+0.51" },
          { size: '2-1/2"', od_mm: "73.02", wall_thickness_mm: "5.16", tolerance_mm: "0~+0.61" },
          { size: '3"', od_mm: "88.90", wall_thickness_mm: "5.49", tolerance_mm: "0~+0.66" },
          { size: '4"', od_mm: "114.30", wall_thickness_mm: "6.02", tolerance_mm: "0~+0.71" },
          { size: '5"', od_mm: "141.30", wall_thickness_mm: "6.55", tolerance_mm: "0~+0.79" },
          { size: '6"', od_mm: "168.28", wall_thickness_mm: "7.11", tolerance_mm: "0~+0.79" },
          { size: '8"', od_mm: "219.08", wall_thickness_mm: "8.18", tolerance_mm: "0~+0.86" },
          { size: '10"', od_mm: "273.05", wall_thickness_mm: "9.27", tolerance_mm: "0~+1.12" },
          { size: '12"', od_mm: "323.85", wall_thickness_mm: "10.31", tolerance_mm: "0~+1.24" },
          { size: '14"', od_mm: "355.60", wall_thickness_mm: "11.10", tolerance_mm: "0~+1.35" },
          { size: '16"', od_mm: "406.40", wall_thickness_mm: "12.70", tolerance_mm: "0~+1.52" },
        ],
      },
    ],
  },
];

async function main() {
  console.log("🌱 Starting seed...");

  await prisma.technicalTable.deleteMany();
  await prisma.specification.deleteMany();
  await prisma.product.deleteMany();
  await prisma.category.deleteMany();

  console.log("🗑️  Cleared existing data");

  for (const category of data) {
    const createdCategory = await prisma.category.create({
      data: { name: category.name, slug: category.slug },
    });

    console.log(`✅ Created category: ${createdCategory.name}`);

    for (const product of category.products) {
      try {
        await prisma.product.create({
          data: {
            name: product.name,
            slug: product.slug,
            preview: product.preview,
            image: product.image,
            images:
              "images" in product && Array.isArray(product.images) ? product.images : [],
            description: product.description,
            categoryId: createdCategory.id,
            specs: { create: product.specs },
            tables: {
              // Each table row stored as a Json blob — exact match to products.json
              create: product.tables.map((row) => ({
                size: "size" in row ? String(row.size ?? "") : "",
                od_mm:
                  "od_mm" in row
                    ? String(row.od_mm ?? "")
                    : "diameter" in row
                      ? String(row.diameter ?? "")
                      : "",
                weight_kg: "weight_kg" in row ? String(row.weight_kg ?? "") : "",
                data: row as unknown as Prisma.InputJsonValue,
              })),
            },
          } as unknown as Prisma.ProductCreateInput,
        });
        console.log(`  📦 Created product: ${product.name}`);
      } catch (e) {
        console.error(`  ❌ Failed: ${product.name}`, e);
      }
    }
  }

  console.log("\n✨ Seed complete!");
  const productCount = await prisma.product.count();
  const categoryCount = await prisma.category.count();
  console.log(`   ${categoryCount} categories, ${productCount} products`);
}

main()
  .catch((e) => {
    console.error("❌ Seed failed:", e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });