import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

const data = [
  {
    name: "PVC Fittings",
    slug: "pvc-fittings",
    products: [
      {
        name: "SCH 80 PVC Union, 2 Inch, 4 Inch Pipe Fitting",
        slug: "sch80-pvc-union",
        image: "/images/products/sch80-pvc-union.jpg",
        preview: "SCH 80 PVC union for pipe connection with easy disassembly for maintenance.",
        description: "SCH 80 PVC union is designed for connecting pipes while allowing easy disassembly for inspection and maintenance. It features a three-piece construction with a strong sealing O-ring, excellent chemical and corrosion resistance, and is manufactured to ASTM D 2467 standard. Suitable for industrial, agricultural, and chemical piping systems.",
        specs: [
          { key: "material", value: "PVC / UPVC" },
          { key: "color", value: "Gray" },
          { key: "standard", value: "ASTM D 2467, SCH 80" },
          { key: "size", value: '1/4" - 4"' },
          { key: "connection", value: "Socket (Solvent Weld)" },
          { key: "pressure_rating", value: "SCH 80" },
          { key: "working_temperature", value: "Up to 60°C" },
          { key: "application", value: "Industrial piping, chemical processing, water treatment" },
        ],
        tables: [
          { size: '1/2"', od_mm: "21.3", weight_kg: "0.08" },
          { size: '3/4"', od_mm: "26.7", weight_kg: "0.12" },
          { size: '1"', od_mm: "33.4", weight_kg: "0.18" },
          { size: '1-1/4"', od_mm: "42.2", weight_kg: "0.28" },
          { size: '1-1/2"', od_mm: "48.3", weight_kg: "0.38" },
          { size: '2"', od_mm: "60.3", weight_kg: "0.58" },
          { size: '2-1/2"', od_mm: "73.0", weight_kg: "0.95" },
          { size: '3"', od_mm: "88.9", weight_kg: "1.45" },
          { size: '4"', od_mm: "114.3", weight_kg: "2.50" },
        ],
      },
      {
        name: "SCH80 PVC Using On The End Cap For Pipe",
        slug: "sch80-pvc-end-cap",
        image: "/images/products/sch80-pvc-end-cap.jpg",
        preview: "SCH 80 PVC end cap for sealing pipe ends in pressure systems.",
        description: "SCH 80 PVC end cap is used to close off the end of a pipe run. Manufactured to ASTM D 2467 standard, it provides a pressure-tight seal and is resistant to a wide range of chemicals.",
        specs: [
          { key: "material", value: "PVC / UPVC" },
          { key: "color", value: "Gray" },
          { key: "standard", value: "ASTM D 2467, SCH 80" },
          { key: "size", value: '1/4" - 12"' },
          { key: "connection", value: "Socket (Solvent Weld)" },
          { key: "pressure_rating", value: "SCH 80" },
          { key: "working_temperature", value: "Up to 60°C" },
        ],
        tables: [
          { size: '1/2"', od_mm: "21.3", weight_kg: "0.03" },
          { size: '3/4"', od_mm: "26.7", weight_kg: "0.05" },
          { size: '1"', od_mm: "33.4", weight_kg: "0.07" },
          { size: '2"', od_mm: "60.3", weight_kg: "0.22" },
          { size: '3"', od_mm: "88.9", weight_kg: "0.55" },
          { size: '4"', od_mm: "114.3", weight_kg: "0.95" },
        ],
      },
      {
        name: "SCH 80 PVC One Piece Flange, 8 Inch Normal Size",
        slug: "sch80-pvc-one-piece-flange",
        image: "/images/products/sch80-pvc-one-piece-flange.jpg",
        preview: "SCH 80 PVC one piece flange for bolted pipe connections up to 8 inch.",
        description: "SCH 80 PVC one piece flange is used to connect piping to equipment such as pumps, valves, and tanks. Manufactured to ASTM D 2467 standard with pre-drilled bolt holes conforming to ANSI B16.5 dimensions.",
        specs: [
          { key: "material", value: "PVC / UPVC" },
          { key: "color", value: "Gray" },
          { key: "standard", value: "ASTM D 2467, SCH 80 / ANSI B16.5" },
          { key: "size", value: '1/2" - 8"' },
          { key: "connection", value: "Socket (Solvent Weld) with bolt flange face" },
          { key: "pressure_rating", value: "SCH 80" },
          { key: "working_temperature", value: "Up to 60°C" },
        ],
        tables: [
          { size: '1"', od_mm: "33.4", weight_kg: "" },
          { size: '2"', od_mm: "60.3", weight_kg: "" },
          { size: '4"', od_mm: "114.3", weight_kg: "" },
          { size: '6"', od_mm: "168.3", weight_kg: "" },
          { size: '8"', od_mm: "219.1", weight_kg: "" },
        ],
      },
      {
        name: "ASTM D 2467 SCH 80 PVC Reducing Tee",
        slug: "sch80-pvc-equal-reducing-tee",
        image: "/images/products/sch80-pvc-equal-reducing-tee.jpg",
        preview: "SCH 80 PVC reducing tee to connect three pipes of equal or different sizes.",
        description: "SCH 80 PVC reducing tee allows branching of a pipeline with a smaller outlet branch. Manufactured to ASTM D 2467 standard.",
        specs: [
          { key: "material", value: "PVC / UPVC" },
          { key: "color", value: "Gray" },
          { key: "standard", value: "ASTM D 2467, SCH 80" },
          { key: "connection", value: "Socket (Solvent Weld)" },
          { key: "pressure_rating", value: "SCH 80" },
          { key: "working_temperature", value: "Up to 60°C" },
        ],
        tables: [
          { size: '3/4" x 1/2"', od_mm: "", weight_kg: "" },
          { size: '1" x 3/4"', od_mm: "", weight_kg: "" },
          { size: '2" x 1-1/2"', od_mm: "", weight_kg: "" },
          { size: '4" x 3"', od_mm: "", weight_kg: "" },
        ],
      },
      {
        name: "NPT Threaded SCH 80 PVC Male Adaptor Coupling",
        slug: "sch80-pvc-male-adaptor",
        image: "/images/products/sch80-pvc-male-adaptor.jpg",
        preview: "SCH 80 PVC male adaptor with NPT thread for socket-to-thread transitions.",
        description: "SCH 80 PVC male adaptor coupling connects a socket-end pipe to an NPT female threaded fitting or equipment port. Manufactured to ASTM D 2467 standard with NPT threads per ANSI/ASME B1.20.1.",
        specs: [
          { key: "material", value: "PVC / UPVC" },
          { key: "color", value: "Gray" },
          { key: "standard", value: "ASTM D 2467, SCH 80" },
          { key: "thread_standard", value: "NPT (ANSI/ASME B1.20.1)" },
          { key: "size", value: '1/4" - 4"' },
          { key: "connection", value: "Socket (Solvent Weld) x NPT Male Thread" },
          { key: "working_temperature", value: "Up to 60°C" },
        ],
        tables: [
          { size: '1/2"', od_mm: "", weight_kg: "" },
          { size: '3/4"', od_mm: "", weight_kg: "" },
          { size: '1"', od_mm: "", weight_kg: "" },
          { size: '2"', od_mm: "", weight_kg: "" },
        ],
      },
      {
        name: "SCH 80 Fitting PVC 45 Degree Elbow Bend Glue Connection",
        slug: "sch80-pvc-45-elbow",
        image: "/images/products/sch80-pvc-45-elbow.jpg",
        preview: "SCH 80 PVC 45° elbow for directional changes in piping via solvent weld.",
        description: "SCH 80 PVC 45 degree elbow provides a 45° change in pipe direction using solvent cement socket connections. Manufactured to ASTM D 2467 standard.",
        specs: [
          { key: "material", value: "PVC / UPVC" },
          { key: "color", value: "Gray" },
          { key: "standard", value: "ASTM D 2467, SCH 80" },
          { key: "angle", value: "45°" },
          { key: "size", value: '1/4" - 8"' },
          { key: "connection", value: "Socket (Solvent Weld)" },
          { key: "working_temperature", value: "Up to 60°C" },
        ],
        tables: [
          { size: '1/2"', od_mm: "", weight_kg: "0.04" },
          { size: '3/4"', od_mm: "", weight_kg: "0.06" },
          { size: '1"', od_mm: "", weight_kg: "0.09" },
          { size: '2"', od_mm: "", weight_kg: "0.32" },
          { size: '4"', od_mm: "", weight_kg: "1.40" },
        ],
      },
      {
        name: "SCH 80 PVC Coupling, Socket Couplers, Using Quick Connection",
        slug: "sch80-pvc-coupling",
        image: "/images/products/sch80-pvc-coupling.jpg",
        preview: "SCH 80 PVC socket coupling for joining two pipes end-to-end.",
        description: "SCH 80 PVC socket coupling connects two pipes of the same diameter end-to-end using solvent cement. Manufactured to ASTM D 2467 standard.",
        specs: [
          { key: "material", value: "PVC / UPVC" },
          { key: "color", value: "Gray" },
          { key: "standard", value: "ASTM D 2467, SCH 80" },
          { key: "size", value: '1/4" - 12"' },
          { key: "connection", value: "Socket x Socket (Solvent Weld)" },
          { key: "working_temperature", value: "Up to 60°C" },
        ],
        tables: [
          { size: '1/2"', od_mm: "", weight_kg: "0.03" },
          { size: '3/4"', od_mm: "", weight_kg: "0.05" },
          { size: '1"', od_mm: "", weight_kg: "0.07" },
          { size: '2"', od_mm: "", weight_kg: "0.25" },
          { size: '4"', od_mm: "", weight_kg: "1.05" },
        ],
      },
      {
        name: "Gray Color SCH 80 PVC 90 Degree Elbow",
        slug: "sch80-pvc-90-elbow",
        image: "/images/products/sch80-pvc-90-elbow.jpg",
        preview: "SCH 80 PVC 90° elbow in gray for right-angle pipe direction changes.",
        description: "SCH 80 PVC 90 degree elbow is used to change pipe direction at a right angle. Manufactured to ASTM D 2467 standard.",
        specs: [
          { key: "material", value: "PVC / UPVC" },
          { key: "color", value: "Gray" },
          { key: "standard", value: "ASTM D 2467, SCH 80" },
          { key: "angle", value: "90°" },
          { key: "size", value: '1/4" - 8"' },
          { key: "connection", value: "Socket (Solvent Weld)" },
          { key: "working_temperature", value: "Up to 60°C" },
        ],
        tables: [
          { size: '1/2"', od_mm: "", weight_kg: "0.05" },
          { size: '3/4"', od_mm: "", weight_kg: "0.08" },
          { size: '1"', od_mm: "", weight_kg: "0.12" },
          { size: '2"', od_mm: "", weight_kg: "0.45" },
          { size: '4"', od_mm: "", weight_kg: "2.00" },
        ],
      },
      {
        name: "ASTM D 1785 Pipe Fittings SCH80 PVC Equal Tee",
        slug: "sch80-pvc-equal-tee",
        image: "/images/products/sch80-pvc-equal-tee.jpg",
        preview: "SCH 80 PVC equal tee for creating equal three-way pipe branches.",
        description: "SCH 80 PVC equal tee provides a T-shaped branch connection where all three outlets are the same size. Manufactured to ASTM D 1785 / ASTM D 2467 standard.",
        specs: [
          { key: "material", value: "PVC / UPVC" },
          { key: "color", value: "Gray" },
          { key: "standard", value: "ASTM D 1785 / ASTM D 2467, SCH 80" },
          { key: "size", value: '1/4" - 8"' },
          { key: "connection", value: "Socket x Socket x Socket (Solvent Weld)" },
          { key: "working_temperature", value: "Up to 60°C" },
        ],
        tables: [
          { size: '1/2"', od_mm: "", weight_kg: "0.06" },
          { size: '3/4"', od_mm: "", weight_kg: "0.10" },
          { size: '1"', od_mm: "", weight_kg: "0.15" },
          { size: '2"', od_mm: "", weight_kg: "0.55" },
          { size: '4"', od_mm: "", weight_kg: "2.40" },
        ],
      },
      {
        name: "Up To 12 Inch SCH 80 PVC Reducers Coupling For Pipe",
        slug: "sch80-pvc-reducer-coupling",
        image: "/images/products/sch80-pvc-reducer-coupling.jpg",
        preview: "SCH 80 PVC reducer coupling to connect pipes of two different diameters up to 12 inch.",
        description: "SCH 80 PVC reducer coupling connects two pipes of different diameters in a straight run. Available in sizes up to 12 inch, manufactured to ASTM D 2467 standard.",
        specs: [
          { key: "material", value: "PVC / UPVC" },
          { key: "color", value: "Gray" },
          { key: "standard", value: "ASTM D 2467, SCH 80" },
          { key: "connection", value: "Socket x Socket (Solvent Weld)" },
          { key: "working_temperature", value: "Up to 60°C" },
        ],
        tables: [
          { size: '3/4" x 1/2"', od_mm: "", weight_kg: "" },
          { size: '1" x 3/4"', od_mm: "", weight_kg: "" },
          { size: '2" x 1-1/2"', od_mm: "", weight_kg: "" },
          { size: '4" x 3"', od_mm: "", weight_kg: "" },
        ],
      },
      {
        name: "SCH 80 PVC Reducer Bushing Connect Pipe And Fittings",
        slug: "sch80-pvc-reducer-bushing",
        image: "/images/products/sch80-pvc-reducer-bushing.jpg",
        preview: "SCH 80 PVC reducer bushing for reducing fittings to a smaller pipe size.",
        description: "SCH 80 PVC reducer bushing is inserted inside a larger socket fitting to reduce it to a smaller pipe size. Manufactured to ASTM D 2467 standard.",
        specs: [
          { key: "material", value: "PVC / UPVC" },
          { key: "color", value: "Gray" },
          { key: "standard", value: "ASTM D 2467, SCH 80" },
          { key: "connection", value: "Spigot x Socket (Solvent Weld)" },
          { key: "working_temperature", value: "Up to 60°C" },
        ],
        tables: [
          { size: '3/4" x 1/2"', od_mm: "", weight_kg: "" },
          { size: '1" x 3/4"', od_mm: "", weight_kg: "" },
          { size: '2" x 1-1/2"', od_mm: "", weight_kg: "" },
        ],
      },
      {
        name: "Type SCH 80 PVC Female Adaptor",
        slug: "sch80-pvc-female-adaptor",
        image: "/images/products/sch80-pvc-female-adaptor.jpg",
        preview: "SCH 80 PVC female adaptor for transitioning from socket to NPT male thread.",
        description: "SCH 80 PVC female adaptor connects a solvent-welded pipe to an NPT male threaded fitting or equipment. Manufactured to ASTM D 2467 with NPT threads per ANSI/ASME B1.20.1 standard.",
        specs: [
          { key: "material", value: "PVC / UPVC" },
          { key: "color", value: "Gray" },
          { key: "standard", value: "ASTM D 2467, SCH 80" },
          { key: "thread_standard", value: "NPT (ANSI/ASME B1.20.1)" },
          { key: "size", value: '1/4" - 4"' },
          { key: "connection", value: "Socket x NPT Female Thread" },
          { key: "working_temperature", value: "Up to 60°C" },
        ],
        tables: [
          { size: '1/2"', od_mm: "", weight_kg: "" },
          { size: '1"', od_mm: "", weight_kg: "" },
          { size: '2"', od_mm: "", weight_kg: "" },
        ],
      },
      {
        name: "SCH80 PVC Tank Adaptor",
        slug: "sch80-pvc-tank-adaptor",
        image: "/images/products/sch80-pvc-tank-adaptor.jpg",
        preview: "SCH 80 PVC tank adaptor for fitting pipes through tank walls.",
        description: "SCH 80 PVC tank adaptor is used to provide a leak-proof through-wall connection on tanks, reservoirs, or vessels. Manufactured to ASTM D 2467 standard.",
        specs: [
          { key: "material", value: "PVC / UPVC" },
          { key: "color", value: "Gray" },
          { key: "standard", value: "ASTM D 2467, SCH 80" },
          { key: "size", value: '1/2" - 4"' },
          { key: "seal", value: "EPDM / NBR rubber gasket" },
          { key: "working_temperature", value: "Up to 60°C" },
        ],
        tables: [
          { size: '1/2"', od_mm: "30", weight_kg: "" },
          { size: '1"', od_mm: "44", weight_kg: "" },
          { size: '2"', od_mm: "76", weight_kg: "" },
        ],
      },
      {
        name: "PVC SCH80 Cross Tee",
        slug: "sch80-pvc-cross-tee",
        image: "/images/products/sch80-pvc-cross-tee.jpg",
        preview: "SCH 80 PVC cross tee for four-way pipe connections in a single fitting.",
        description: "SCH 80 PVC cross tee provides four equal-size socket outlets in a cross configuration. Manufactured to ASTM D 2467 standard.",
        specs: [
          { key: "material", value: "PVC / UPVC" },
          { key: "color", value: "Gray" },
          { key: "standard", value: "ASTM D 2467, SCH 80" },
          { key: "size", value: '1/2" - 4"' },
          { key: "connection", value: "Socket x Socket x Socket x Socket (Solvent Weld)" },
          { key: "working_temperature", value: "Up to 60°C" },
        ],
        tables: [
          { size: '1/2"', od_mm: "", weight_kg: "0.09" },
          { size: '1"', od_mm: "", weight_kg: "0.22" },
          { size: '2"', od_mm: "", weight_kg: "0.85" },
          { size: '4"', od_mm: "", weight_kg: "3.80" },
        ],
      },
      {
        name: "PVC Bend",
        slug: "pvc-bend",
        image: "/images/products/pvc-bend.jpg",
        preview: "PVC pipe bend for flexible directional changes in piping layouts.",
        description: "PVC bend provides directional changes in piping systems and is available in various angles including 11.25°, 22.5°, 45°, and 90°.",
        specs: [
          { key: "material", value: "PVC / UPVC" },
          { key: "color", value: "Gray" },
          { key: "angles_available", value: "11.25°, 22.5°, 45°, 90°" },
          { key: "size", value: '1/2" - 12"' },
          { key: "connection", value: "Socket (Solvent Weld) or Rubber Ring" },
          { key: "working_temperature", value: "Up to 60°C" },
        ],
        tables: [
          { size: '1/2"', od_mm: "", weight_kg: "" },
          { size: '1"', od_mm: "", weight_kg: "" },
          { size: '2"', od_mm: "", weight_kg: "" },
          { size: '4"', od_mm: "", weight_kg: "" },
        ],
      },
      {
        name: "PVC Pipe Clip",
        slug: "pvc-pipe-clip",
        image: "/images/products/pvc-pipe-clip.jpg",
        preview: "PVC pipe clip for securing and supporting pipes along walls and structures.",
        description: "PVC pipe clip is used to support, guide, and secure PVC pipes to walls, ceilings, or structural supports. Resistant to corrosion and UV degradation.",
        specs: [
          { key: "material", value: "PVC" },
          { key: "color", value: "Gray" },
          { key: "size", value: "Fits pipe OD 20mm - 160mm" },
          { key: "mounting", value: "Single screw or double screw" },
        ],
        tables: [
          { size: '1/2"', od_mm: "20", weight_kg: "" },
          { size: '1"', od_mm: "32", weight_kg: "" },
          { size: '2"', od_mm: "63", weight_kg: "" },
          { size: '4"', od_mm: "110", weight_kg: "" },
        ],
      },
    ],
  },
  {
    name: "BS Standard Female Threaded Fittings",
    slug: "bs-standard-female-threaded-fittings",
    products: [
      {
        name: "PVC Double Female Socket (BS Standard)",
        slug: "bs-pvc-double-female-socket",
        image: "/images/products/bs-pvc-double-female-socket.jpg",
        preview: "BS standard PVC double female socket for joining two male-threaded pipes or fittings.",
        description: "BS standard PVC double female socket connects two male BSPT threaded pipes or fittings in a straight run. Manufactured to BS EN 10226-2 / BS-21 standard.",
        specs: [
          { key: "material", value: "PVC / UPVC" },
          { key: "color", value: "Gray" },
          { key: "standard", value: "BS EN 10226-2 / BS-21" },
          { key: "thread_standard", value: "BSPT (BS-21)" },
          { key: "size", value: "20mm - 63mm" },
          { key: "working_temperature", value: "Up to 60°C" },
        ],
        tables: [
          { size: "20mm", od_mm: "27.5", weight_kg: "" },
          { size: "25mm", od_mm: "33.3", weight_kg: "" },
          { size: "32mm", od_mm: "40.5", weight_kg: "" },
          { size: "50mm", od_mm: "58.3", weight_kg: "" },
          { size: "63mm", od_mm: "75", weight_kg: "" },
        ],
      },
      {
        name: "PVC Three Side Threaded Female Tee (BS Standard)",
        slug: "bs-pvc-female-tee",
        image: "/images/products/bs-pvc-female-tee.jpg",
        preview: "BS standard PVC female tee with BSPT female threads on all three outlets.",
        description: "BS standard PVC three-side threaded female tee provides a T-shaped branch connection with BSPT female threads on all three outlets. Manufactured to BS EN 10226-2 / BS-21 standard.",
        specs: [
          { key: "material", value: "PVC / UPVC" },
          { key: "color", value: "Gray" },
          { key: "standard", value: "BS EN 10226-2 / BS-21" },
          { key: "thread_standard", value: "BSPT (BS-21)" },
          { key: "size", value: '1/2" - 1-1/4"' },
          { key: "working_temperature", value: "Up to 60°C" },
        ],
        tables: [
          { size: '1/2"', od_mm: "20", weight_kg: "" },
          { size: '3/4" x 1/2"', od_mm: "26.8", weight_kg: "" },
          { size: '1-1/4"', od_mm: "41.8", weight_kg: "" },
        ],
      },
      {
        name: "PVC Double Threaded Female Elbow 90° (BS Standard)",
        slug: "bs-pvc-double-female-elbow",
        image: "/images/products/bs-pvc-double-female-elbow.jpg",
        preview: "BS standard PVC 90° elbow with BSPT female threads on both ends.",
        description: "BS standard PVC double threaded female elbow provides a 90° directional change with BSPT female threads on both ends. Manufactured to BS EN 10226-2 / BS-21 standard.",
        specs: [
          { key: "material", value: "PVC / UPVC" },
          { key: "color", value: "Gray" },
          { key: "standard", value: "BS EN 10226-2 / BS-21" },
          { key: "thread_standard", value: "BSPT (BS-21)" },
          { key: "angle", value: "90°" },
          { key: "working_temperature", value: "Up to 60°C" },
        ],
        tables: [
          { size: '32mm x 1"', od_mm: "41", weight_kg: "" },
        ],
      },
    ],
  },
  {
    name: "PVC Valve",
    slug: "pvc-valve",
    products: [
      {
        name: "PVC Sampling Valve",
        slug: "pvc-sampling-valve",
        image: "/images/products/pvc-sampling-valve.jpg",
        preview: "PVC sampling valve for drawing fluid samples from pipelines without shutting down the system.",
        description: "PVC sampling valve is a quarter-turn plug-type valve designed for extracting fluid samples from pipelines or tanks in chemical processing, water treatment, and laboratory applications.",
        specs: [
          { key: "material", value: "PVC / UPVC" },
          { key: "color", value: "Black" },
          { key: "standard", value: "ISO 727" },
          { key: "size", value: '1/2" - 2"' },
          { key: "seal", value: "EPDM / FKM (Viton)" },
          { key: "pressure_rating", value: "PN10" },
          { key: "working_temperature", value: "Up to 60°C" },
        ],
        tables: [
          { size: '1/2"', od_mm: "21.3", weight_kg: "" },
          { size: '1"', od_mm: "33.4", weight_kg: "" },
          { size: '2"', od_mm: "60.3", weight_kg: "" },
        ],
      },
      {
        name: "PVC General Handle Butterfly Valve ASTM Standard",
        slug: "pvc-butterfly-valve-astm",
        image: "/images/products/pvc-butterfly-valve-astm.jpg",
        preview: "ASTM standard PVC butterfly valve with general lever handle for flow control in large pipe systems.",
        description: "PVC general handle butterfly valve is a quarter-turn wafer-style valve used to regulate or isolate flow in large-diameter pipe systems.",
        specs: [
          { key: "material", value: "PVC body and disc, stainless steel stem" },
          { key: "color", value: "Gray" },
          { key: "standard", value: "ASTM" },
          { key: "size", value: '2" - 12" (DN50 - DN300)' },
          { key: "connection", value: "Wafer (flange-mounted between flanges)" },
          { key: "seat_material", value: "EPDM / NBR" },
          { key: "pressure_rating", value: "PN10 (150 PSI)" },
          { key: "working_temperature", value: "Up to 60°C" },
        ],
        tables: [
          { size: '2"', od_mm: "DN50", weight_kg: "" },
          { size: '4"', od_mm: "DN100", weight_kg: "" },
          { size: '6"', od_mm: "DN150", weight_kg: "" },
          { size: '8"', od_mm: "DN200", weight_kg: "" },
          { size: '12"', od_mm: "DN300", weight_kg: "" },
        ],
      },
      {
        name: "PVC Compact Ball Valve",
        slug: "pvc-compact-ball-valve",
        image: "/images/products/pvc-compact-ball-valve.jpg",
        preview: "PVC compact ball valve for on/off flow control in tight-space piping applications.",
        description: "PVC compact ball valve is a space-saving quarter-turn ball valve with socket or threaded ends. Features a full-bore PVC ball, PTFE seats, and EPDM O-ring seals.",
        specs: [
          { key: "material", value: "PVC / UPVC body, PVC ball, PTFE seats" },
          { key: "color", value: "Gray" },
          { key: "standard", value: "ISO 727 / DIN" },
          { key: "size", value: '1/4" - 2" (DN8 - DN50)' },
          { key: "seal", value: "PTFE seats, EPDM O-rings" },
          { key: "pressure_rating", value: "PN10 - PN16" },
          { key: "working_temperature", value: "Up to 60°C" },
        ],
        tables: [
          { size: '1/2"', od_mm: "DN15", weight_kg: "" },
          { size: '3/4"', od_mm: "DN20", weight_kg: "" },
          { size: '1"', od_mm: "DN25", weight_kg: "" },
          { size: '2"', od_mm: "DN50", weight_kg: "" },
        ],
      },
      {
        name: "PVC Threaded Ball Valve Standard",
        slug: "pvc-threaded-ball-valve",
        image: "/images/products/pvc-threaded-ball-valve.jpg",
        preview: "PVC ball valve with male or female NPT/BSP threads for easy threaded pipe installation.",
        description: "PVC threaded ball valve provides quarter-turn on/off flow control with NPT or BSP threaded ends for direct connection to threaded pipes or fittings.",
        specs: [
          { key: "material", value: "PVC / UPVC body and ball, PTFE seats" },
          { key: "color", value: "Gray" },
          { key: "standard", value: "ISO 727" },
          { key: "thread_standard", value: "NPT or BSP" },
          { key: "size", value: '1/4" - 4" (DN8 - DN100)' },
          { key: "pressure_rating", value: "PN10 - PN16" },
          { key: "working_temperature", value: "Up to 60°C" },
        ],
        tables: [
          { size: '1/2"', od_mm: "DN15", weight_kg: "" },
          { size: '1"', od_mm: "DN25", weight_kg: "" },
          { size: '2"', od_mm: "DN50", weight_kg: "" },
          { size: '4"', od_mm: "DN100", weight_kg: "" },
        ],
      },
      {
        name: "PVC True Union Ball Valve",
        slug: "pvc-true-union-ball-valve",
        image: "/images/products/pvc-true-union-ball-valve.jpg",
        preview: "PVC true union ball valve for in-line removal and maintenance without disturbing pipework.",
        description: "PVC true union ball valve features a two-piece union body construction that allows the valve to be removed from the pipeline for inspection or replacement without cutting the pipe.",
        specs: [
          { key: "material", value: "PVC / UPVC body and ball, PTFE seats" },
          { key: "color", value: "Gray" },
          { key: "standard", value: "ASTM F1970 / ISO 727" },
          { key: "size", value: '1/2" - 4" (DN15 - DN100)' },
          { key: "seal", value: "PTFE seats, EPDM O-rings" },
          { key: "pressure_rating", value: "PN10 - PN16" },
          { key: "working_temperature", value: "Up to 60°C" },
        ],
        tables: [
          { size: '1/2"', od_mm: "DN15", weight_kg: "" },
          { size: '1"', od_mm: "DN25", weight_kg: "" },
          { size: '2"', od_mm: "DN50", weight_kg: "" },
          { size: '4"', od_mm: "DN100", weight_kg: "" },
        ],
      },
      {
        name: "PVC Foot Valve",
        slug: "pvc-foot-valve",
        image: "/images/products/pvc-foot-valve.jpg",
        preview: "PVC foot valve installed at pump inlet to maintain prime and prevent backflow.",
        description: "PVC foot valve is a spring-loaded non-return valve installed at the bottom of a suction pipe to keep the pump primed and prevent backflow when the pump stops.",
        specs: [
          { key: "material", value: "PVC / UPVC body, stainless steel spring, EPDM disc" },
          { key: "color", value: "Gray" },
          { key: "standard", value: "ISO 727" },
          { key: "size", value: '1/2" - 6" (DN15 - DN150)' },
          { key: "seal", value: "EPDM disc, NBR O-ring" },
          { key: "pressure_rating", value: "PN10" },
          { key: "working_temperature", value: "Up to 60°C" },
        ],
        tables: [
          { size: '1/2"', od_mm: "DN15", weight_kg: "" },
          { size: '1"', od_mm: "DN25", weight_kg: "" },
          { size: '2"', od_mm: "DN50", weight_kg: "" },
          { size: '4"', od_mm: "DN100", weight_kg: "" },
          { size: '6"', od_mm: "DN150", weight_kg: "" },
        ],
      },
      {
        name: "PVC Double Union Ball Check Valve",
        slug: "pvc-double-union-ball-check-valve",
        image: "/images/products/pvc-double-union-ball-check-valve.jpg",
        preview: "PVC double union ball check valve to prevent backflow with easy in-line removal.",
        description: "PVC double union ball check valve uses a free-floating PVC ball to prevent reverse flow in piping systems. The double union design allows the valve body to be removed from the pipeline without cutting pipe.",
        specs: [
          { key: "material", value: "PVC / UPVC body, PVC ball, EPDM seals" },
          { key: "color", value: "Gray" },
          { key: "standard", value: "ISO 727 / ASTM" },
          { key: "size", value: '1/2" - 4" (DN15 - DN100)' },
          { key: "pressure_rating", value: "PN10" },
          { key: "working_temperature", value: "Up to 60°C" },
        ],
        tables: [
          { size: '1/2"', od_mm: "DN15", weight_kg: "" },
          { size: '1"', od_mm: "DN25", weight_kg: "" },
          { size: '2"', od_mm: "DN50", weight_kg: "" },
          { size: '4"', od_mm: "DN100", weight_kg: "" },
        ],
      },
      {
        name: "PVC Swing Check Valve",
        slug: "pvc-swing-check-valve",
        image: "/images/products/pvc-swing-check-valve.jpg",
        preview: "PVC swing check valve allowing flow in one direction with gravity-assisted closure.",
        description: "PVC swing check valve uses a hinged disc that swings open under forward flow and closes by gravity when flow stops or reverses.",
        specs: [
          { key: "material", value: "PVC / UPVC body, PVC disc, stainless steel hinge pin" },
          { key: "color", value: "Gray" },
          { key: "standard", value: "ISO 727 / BS 5153" },
          { key: "size", value: '1/2" - 6" (DN15 - DN150)' },
          { key: "seal", value: "EPDM" },
          { key: "pressure_rating", value: "PN10" },
          { key: "working_temperature", value: "Up to 60°C" },
        ],
        tables: [
          { size: '1/2"', od_mm: "DN15", weight_kg: "" },
          { size: '1"', od_mm: "DN25", weight_kg: "" },
          { size: '2"', od_mm: "DN50", weight_kg: "" },
          { size: '4"', od_mm: "DN100", weight_kg: "" },
        ],
      },
      {
        name: "PVC Wafer Check Valve",
        slug: "pvc-wafer-check-valve",
        image: "/images/products/pvc-wafer-check-valve.jpg",
        preview: "PVC wafer check valve with dual-plate spring-assisted closure for compact in-line backflow prevention.",
        description: "PVC wafer check valve is a slim, lightweight dual-plate check valve designed to fit between pipe flanges.",
        specs: [
          { key: "material", value: "PVC / UPVC body, PVC discs, stainless steel spring and hinge pin" },
          { key: "color", value: "Gray" },
          { key: "standard", value: "API 594 / ISO 13709" },
          { key: "size", value: '2" - 12" (DN50 - DN300)' },
          { key: "seal", value: "EPDM / NBR" },
          { key: "pressure_rating", value: "PN10 - PN16" },
          { key: "working_temperature", value: "Up to 60°C" },
        ],
        tables: [
          { size: '2"', od_mm: "DN50", weight_kg: "" },
          { size: '4"', od_mm: "DN100", weight_kg: "" },
          { size: '6"', od_mm: "DN150", weight_kg: "" },
          { size: '12"', od_mm: "DN300", weight_kg: "" },
        ],
      },
      {
        name: "PVC Air Relief Valve 1 Inch",
        slug: "pvc-air-relief-valve-1inch",
        image: "/images/products/pvc-air-relief-valve-1inch.jpg",
        preview: "1 inch PVC air relief valve to automatically release trapped air from pressurized pipelines.",
        description: "PVC air relief valve (1 inch) automatically vents trapped air from pressurized water pipelines to prevent air locks and maintain efficient flow.",
        specs: [
          { key: "material", value: "PVC / UPVC body, stainless steel float" },
          { key: "color", value: "Blue and black" },
          { key: "size", value: '1" (DN25)' },
          { key: "connection", value: "NPT Male Thread or Flanged" },
          { key: "seal", value: "EPDM" },
          { key: "pressure_rating", value: "PN10" },
          { key: "working_temperature", value: "Up to 60°C" },
        ],
        tables: [
          { size: '1"', od_mm: "DN25", weight_kg: "" },
        ],
      },
      {
        name: "PVC Air Relief Valve 2 Inch",
        slug: "pvc-air-relief-valve-2inch",
        image: "/images/products/pvc-air-relief-valve-2inch.jpg",
        preview: "2 inch PVC air relief valve for high-capacity air venting in large water pipelines.",
        description: "PVC air relief valve (2 inch) provides high-capacity automatic air venting for larger-diameter pressurized water pipelines.",
        specs: [
          { key: "material", value: "PVC / UPVC body, stainless steel float" },
          { key: "color", value: "Blue and black" },
          { key: "size", value: '2" (DN50)' },
          { key: "pressure_rating", value: "PN10" },
          { key: "working_temperature", value: "Up to 60°C" },
        ],
        tables: [
          { size: '2"', od_mm: "DN50", weight_kg: "" },
        ],
      },
      {
        name: "PVC (NRV) No Return Valve 6 Inch",
        slug: "pvc-nrv-6inch",
        image: "/images/products/pvc-nrv-6inch.jpg",
        preview: "6 inch PVC non-return valve (NRV) for large-bore backflow prevention.",
        description: "PVC no-return valve (NRV) 6 inch is a large-bore check valve that allows flow in one direction only and prevents reverse flow.",
        specs: [
          { key: "material", value: "PVC / UPVC body, PVC or rubber-lined disc" },
          { key: "color", value: "Gray" },
          { key: "standard", value: "ISO 727 / BS 5153" },
          { key: "size", value: '6" (DN150)' },
          { key: "connection", value: "Flanged (ANSI 150 / PN10)" },
          { key: "pressure_rating", value: "PN10" },
          { key: "working_temperature", value: "Up to 60°C" },
        ],
        tables: [
          { size: '6"', od_mm: "DN150", weight_kg: "" },
        ],
      },
    ],
  },
  {
    name: "PVC Disc Filters And Strainers",
    slug: "pvc-disc-filters-and-strainers",
    products: [
      {
        name: "PVC Y-Strainer",
        slug: "pvc-y-strainer",
        image: "/images/products/pvc-y-strainer.jpg",
        preview: "PVC Y-strainer to filter debris and particulates from piping systems.",
        description: "PVC Y-strainer removes solid particles, debris, and sediment from liquid pipelines to protect downstream equipment such as pumps, meters, valves, and nozzles.",
        specs: [
          { key: "material", value: "PVC / UPVC body, stainless steel screen" },
          { key: "color", value: "Dark blue and Black" },
          { key: "standard", value: "ISO 727" },
          { key: "size", value: '1/2" - 4" (DN15 - DN100)' },
          { key: "screen_mesh", value: "20 mesh, 40 mesh, 80 mesh" },
          { key: "pressure_rating", value: "PN10 - PN16" },
          { key: "working_temperature", value: "Up to 60°C" },
        ],
        tables: [
          { size: '1/2"', od_mm: "DN15", weight_kg: "" },
          { size: '1"', od_mm: "DN25", weight_kg: "" },
          { size: '2"', od_mm: "DN50", weight_kg: "" },
          { size: '4"', od_mm: "DN100", weight_kg: "" },
        ],
      },
      {
        name: "PVC Disc Filter",
        slug: "pvc-disc-filter",
        image: "/images/products/pvc-disc-filter.jpg",
        preview: "PVC disc filter using stacked grooved discs for fine filtration in irrigation and water treatment systems.",
        description: "PVC disc filter is a high-efficiency filtration device that uses a stack of grooved PVC or polypropylene discs compressed together to form a three-dimensional filtration matrix.",
        specs: [
          { key: "material", value: "PVC / UPVC housing, polypropylene disc stack" },
          { key: "color", value: "Black" },
          { key: "size", value: '3/4" - 3" inlet/outlet' },
          { key: "filtration_rating", value: "20 micron, 55 micron, 100 micron, 130 micron, 200 micron" },
          { key: "pressure_rating", value: "PN8 - PN10" },
          { key: "working_temperature", value: "Up to 50°C" },
          { key: "backwash", value: "Manual or automatic" },
        ],
        tables: [
          { size: '3/4"', od_mm: "DN20", weight_kg: "" },
          { size: '1"', od_mm: "DN25", weight_kg: "" },
          { size: '2"', od_mm: "DN50", weight_kg: "" },
          { size: '3"', od_mm: "DN80", weight_kg: "" },
        ],
      },
    ],
  },
  {
    name: "PVC Pipes",
    slug: "pvc-pipes",
    products: [
      {
        name: "PVC Pipe SCH 80",
        slug: "sch80-pvc-pipe",
        image: "/images/products/sch80-pvc-pipe.jpg",
        preview: "SCH 80 gray PVC pipe manufactured to ASTM D1785 standard for high-pressure industrial and chemical piping systems.",
        description: "SCH 80 PVC pipe is manufactured to ASTM D1785 standard using Polyvinyl Chloride material. Featuring thicker walls than SCH 40, it is designed for high-pressure applications in industrial, chemical processing, and water treatment systems.",
        specs: [
          { key: "material", value: "PVC / UPVC (Polyvinyl Chloride)" },
          { key: "color", value: "Gray" },
          { key: "standard", value: "ASTM D1785, SCH 80" },
          { key: "size", value: '1/2" - 16"' },
          { key: "connection", value: "Socket, Rubber Ring, Plain End" },
          { key: "working_temperature", value: "Up to 60°C" },
          { key: "warranty", value: "50 years" },
          { key: "certifications", value: "SGS, NSF, ISO, COC" },
        ],
        tables: [
          { size: '1/2"', od_mm: "21.34", weight_kg: "3.73" },
          { size: '3/4"', od_mm: "26.67", weight_kg: "3.91" },
          { size: '1"', od_mm: "33.40", weight_kg: "4.55" },
          { size: '1-1/2"', od_mm: "48.26", weight_kg: "5.08" },
          { size: '2"', od_mm: "60.32", weight_kg: "5.54" },
          { size: '3"', od_mm: "88.90", weight_kg: "7.62" },
          { size: '4"', od_mm: "114.30", weight_kg: "8.56" },
          { size: '6"', od_mm: "168.28", weight_kg: "10.97" },
          { size: '8"', od_mm: "219.08", weight_kg: "12.70" },
          { size: '12"', od_mm: "323.85", weight_kg: "17.45" },
        ],
      },
      {
        name: "PVC Pipe SCH 40",
        slug: "sch40-pvc-pipe",
        image: "/images/products/sch40-pvc-pipe.jpg",
        preview: "SCH 40 PVC pipe to ASTM D1785 standard for water supply, irrigation, and general industrial applications.",
        description: "SCH 40 PVC pipe is manufactured to ASTM D1785 standard using PVC/UPVC material. It is the most widely used schedule for general-purpose water supply, irrigation, drainage, and light industrial piping.",
        specs: [
          { key: "material", value: "PVC / UPVC (Polyvinyl Chloride)" },
          { key: "color", value: "Gray" },
          { key: "standard", value: "ASTM D1785, SCH 40" },
          { key: "size", value: '1/2" - 24"' },
          { key: "connection", value: "Socket" },
          { key: "working_temperature", value: "Up to 60°C" },
          { key: "warranty", value: "50 years" },
          { key: "certifications", value: "SGS, NSF, ISO, COC" },
        ],
        tables: [
          { size: '1/2"', od_mm: "21.34", weight_kg: "2.77" },
          { size: '3/4"', od_mm: "26.67", weight_kg: "2.87" },
          { size: '1"', od_mm: "33.40", weight_kg: "3.38" },
          { size: '1-1/2"', od_mm: "48.26", weight_kg: "3.68" },
          { size: '2"', od_mm: "60.32", weight_kg: "3.91" },
          { size: '3"', od_mm: "88.90", weight_kg: "5.49" },
          { size: '4"', od_mm: "114.30", weight_kg: "6.02" },
          { size: '6"', od_mm: "168.28", weight_kg: "7.11" },
          { size: '8"', od_mm: "219.08", weight_kg: "8.18" },
          { size: '12"', od_mm: "323.85", weight_kg: "10.31" },
        ],
      },
    ],
  },
];

async function main() {
  console.log("🌱 Starting seed...");

  // Clear existing data
  await prisma.technicalTable.deleteMany();
  await prisma.specification.deleteMany();
  await prisma.product.deleteMany();
  await prisma.category.deleteMany();

  console.log("🗑️  Cleared existing data");

  for (const category of data) {
    const createdCategory = await prisma.category.create({
      data: {
        name: category.name,
        slug: category.slug,
      },
    });

    console.log(`✅ Created category: ${createdCategory.name}`);

    for (const product of category.products) {
      await prisma.product.create({
        data: {
          name: product.name,
          slug: product.slug,
          image: product.image,
          description: product.description,
          categoryId: createdCategory.id,
          specs: {
            create: product.specs,
          },
          tables: {
            create: product.tables,
          },
        },
      });

      console.log(`  📦 Created product: ${product.name}`);
    }
  }

  console.log("\n✨ Seed complete!");
  const productCount = await prisma.product.count();
  const categoryCount = await prisma.category.count();
  console.log(`   ${categoryCount} categories, ${productCount} products`);
}

main()
  .catch((e) => {
    console.error("❌ Seed failed:", e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });